// Adopts the UIScene life cycle in the CNG-generated iOS project.
//
// iOS 27 asserts at launch (SIGTRAP in `___UIApplicationEvaluateRuntimeIssueForNoSceneLifecycleAdoption`)
// unless the app adopts scenes. `expo@57` already ships the runtime side (`ExpoAppSceneDelegate`,
// `ExpoReactNativeFactoryProvider`), but the SDK 57 prebuild template does not use it; the SDK 58
// template does. This plugin applies the same three edits so `mobile/ios/` stays disposable:
//   1. AppDelegate conforms to ExpoReactNativeFactoryProvider and stops creating the window /
//      starting React Native (the scene delegate does that now).
//   2. A `SceneDelegate` subclass of ExpoAppSceneDelegate. It is appended to AppDelegate.swift
//      (already in the Xcode target) so no .pbxproj edit is needed.
//   3. `UIApplicationSceneManifest` in Info.plist pointing at that SceneDelegate.
//
// Remove this plugin once the SDK 57 template (or an upgrade to SDK 58) does it natively.
const { withAppDelegate, withInfoPlist } = require("expo/config-plugins");

const CLASS_DECLARATION = "class AppDelegate: ExpoAppDelegate {";
const CLASS_DECLARATION_WITH_PROVIDER =
  "class AppDelegate: ExpoAppDelegate, ExpoReactNativeFactoryProvider {";

// The window + startReactNative block of the SDK 57 template, up to and including `#endif`.
const WINDOW_BLOCK =
  /[ \t]*#if os\(iOS\) \|\| os\(tvOS\)\n[ \t]*window = UIWindow\(frame: UIScreen\.main\.bounds\)\n[ \t]*factory\.startReactNative\([\s\S]*?\)\n#endif\n\n?/;

const SCENE_DELEGATE = `
@objc(SceneDelegate)
class SceneDelegate: ExpoAppSceneDelegate {
  // Extension point for config plugins.
}
`;

const WINDOW_REPLACEMENT =
  "    // The window is created and React Native is started by `SceneDelegate` under the\n" +
  "    // scene-based life cycle (required by the iOS 27 SDK).\n";

/**
 * @param {string} contents AppDelegate.swift as generated by the SDK 57 template.
 * @returns {string} contents adopting the scene life cycle; unchanged if already adopted.
 */
function patchAppDelegate(contents) {
  if (contents.includes("ExpoReactNativeFactoryProvider")) {
    return contents;
  }
  if (!contents.includes(CLASS_DECLARATION) || !WINDOW_BLOCK.test(contents)) {
    // Fail loudly: a silent no-op would only resurface as the iOS 27 launch crash.
    throw new Error(
      "withIosSceneLifecycle: the generated AppDelegate.swift no longer matches the SDK 57 " +
        "template. Update plugins/withIosSceneLifecycle.js (or delete it if the template " +
        "adopts UIScene natively).",
    );
  }
  return (
    contents
      .replace(CLASS_DECLARATION, CLASS_DECLARATION_WITH_PROVIDER)
      .replace(WINDOW_BLOCK, WINDOW_REPLACEMENT)
      .trimEnd() +
    "\n" +
    SCENE_DELEGATE
  );
}

/** @returns {Record<string, unknown>} the manifest, or the existing one if already set. */
function sceneManifest(existing) {
  if (existing) {
    return existing;
  }
  return {
    UIApplicationSupportsMultipleScenes: false,
    UISceneConfigurations: {
      UIWindowSceneSessionRoleApplication: [
        {
          UISceneConfigurationName: "Default Configuration",
          UISceneDelegateClassName: "$(PRODUCT_MODULE_NAME).SceneDelegate",
        },
      ],
    },
  };
}

function withIosSceneLifecycle(config) {
  config = withAppDelegate(config, (mod) => {
    if (mod.modResults.language !== "swift") {
      throw new Error("withIosSceneLifecycle: only a Swift AppDelegate is supported.");
    }
    mod.modResults.contents = patchAppDelegate(mod.modResults.contents);
    return mod;
  });
  return withInfoPlist(config, (mod) => {
    mod.modResults.UIApplicationSceneManifest = sceneManifest(
      mod.modResults.UIApplicationSceneManifest,
    );
    return mod;
  });
}

module.exports = withIosSceneLifecycle;
module.exports.patchAppDelegate = patchAppDelegate;
module.exports.sceneManifest = sceneManifest;
