// Builds ./ds-bundle (tokens-only design system) from the app theme + design/ docs.
// Run from repo root: node .design-sync/build.mjs
import { readFileSync, writeFileSync, mkdirSync, cpSync, rmSync, readdirSync } from "node:fs";
import { join } from "node:path";

const OUT = "ds-bundle";
const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
const read = (p) => readFileSync(p, "utf8");

function extract(file, name) {
  const m = read(file).match(new RegExp(`export const ${name}\\s*=\\s*(\\{[\\s\\S]*?\\}|\\[[\\s\\S]*?\\])\\s*(?:as const)?\\s*(?:satisfies \\w+)?\\s*;`));
  if (!m) throw new Error(`cannot find ${name} in ${file}`);
  return new Function(`return (${m[1]})`)();
}
const T = "mobile/src/lib/theme";
const dark = extract(`${T}/tokens.ts`, "darkTokens");
const light = extract(`${T}/tokens.ts`, "lightTokens");
const covers = extract(`${T}/tokens.ts`, "coverColors");
const family = extract(`${T}/typography.ts`, "family");
const size = extract(`${T}/typography.ts`, "size");
const radius = extract(`${T}/metrics.ts`, "radius");
const spacing = extract(`${T}/metrics.ts`, "spacing");
const layout = extract(`${T}/metrics.ts`, "layout");
const iconSize = extract(`${T}/metrics.ts`, "iconSize");
const blur = extract(`${T}/metrics.ts`, "blurIntensity");
const motion = extract(`${T}/metrics.ts`, "motion");
const muteSat = Number(read(`${T}/metrics.ts`).match(/coverMuteSaturation\s*=\s*([\d.]+)/)[1]);

const vars = (obj, prefix, unit = "px") =>
  Object.entries(obj).map(([k, v]) => `  --${prefix}-${kebab(k)}: ${v}${typeof v === "number" ? unit : ""};`).join("\n");
const colorBlock = (o) => Object.entries(o).map(([k, v]) => `  --color-${kebab(k)}: ${v};`).join("\n");

rmSync(OUT, { recursive: true, force: true });
for (const d of ["tokens", "fonts", "guidelines/screens"]) mkdirSync(join(OUT, d), { recursive: true });

// fonts
const fdir = (pkg, w) => `node_modules/.pnpm/@expo-google-fonts+${pkg.split("@")[0]}@${pkg.split("@")[1]}/node_modules/@expo-google-fonts/${pkg.split("@")[0]}/${w}`;
const fonts = [
  ["manrope@0.4.2", "400Regular", "Manrope"], ["manrope@0.4.2", "500Medium", "Manrope"],
  ["manrope@0.4.2", "700Bold", "Manrope"], ["manrope@0.4.2", "800ExtraBold", "Manrope"],
  ["ibm-plex-mono@0.4.1", "500Medium", "IBMPlexMono"],
];
let faces = "";
for (const [pkg, w, fam] of fonts) {
  const file = `${fam}_${w}.ttf`;
  cpSync(join(fdir(pkg, w), file), join(OUT, "fonts", file));
  faces += `@font-face { font-family: "${fam}_${w}"; src: url("../fonts/${file}") format("truetype"); font-display: swap; }\n`;
}
writeFileSync(join(OUT, "tokens/fonts.css"), `/* generated by .design-sync/build.mjs */\n${faces}`);

// colours: dark by default OS-less? follow system; data-theme overrides
const shared = covers.map((c, i) => `  --cover-${i + 1}: ${c};`).join("\n");
writeFileSync(join(OUT, "tokens/colors.css"), `/* generated from mobile/src/lib/theme/tokens.ts */
:root {
  color-scheme: light dark;
${colorBlock(light)}
${shared}
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${colorBlock(dark)}
  }
}
:root[data-theme="dark"] {
${colorBlock(dark)}
}
`);

writeFileSync(join(OUT, "tokens/metrics.css"), `/* generated from mobile/src/lib/theme/metrics.ts (screenX..section = layout spacing, xs..xxl = inner scale) */
:root {
${vars(radius, "radius")}
  --space-screen-x: ${spacing.screenX}px;
  --space-gap: ${spacing.gap}px;
  --space-block: ${spacing.block}px;
  --space-section: ${spacing.section}px;
${["xs", "sm", "md", "lg", "xl", "xxl"].map((k) => `  --space-${k}: ${spacing[k]}px;`).join("\n")}
${vars(layout, "layout")}
${vars(iconSize, "icon-size")}
${vars(blur, "blur")}
${vars(motion, "motion", "ms")}
  --cover-mute-saturation: ${muteSat};
}
`);

const roles = {
  hero: ["display", "hero"], "auth-title": ["display", "authTitle"], h1: ["display", "h1"], "city-hero": ["display", "cityHero"],
  "card-title": ["display", "cardTitle"], h2: ["bold", "h2"], button: ["bold", "body"], body: ["medium", "body"],
  small: ["medium", "small"], caption: ["medium", "caption"], micro: ["medium", "micro"], mono: ["mono", "body"], "mono-small": ["mono", "small"],
};
writeFileSync(join(OUT, "tokens/typography.css"), `/* generated from mobile/src/lib/theme/typography.ts. One face per weight; never use font-weight 600. */
:root {
${Object.entries(family).map(([k, v]) => `  --font-${kebab(k)}: "${v}", system-ui, sans-serif;`).join("\n")}
${vars(size, "font-size")}
}
${Object.entries(roles).map(([r, [f, s]]) => `.type-${r} { font-family: var(--font-${f}); font-size: var(--font-size-${kebab(s)}); }`).join("\n")}
`);

writeFileSync(join(OUT, "styles.css"), `/* TripPlanner design tokens. Import closure = tokens/*.css */
@import url("tokens/fonts.css");
@import url("tokens/colors.css");
@import url("tokens/metrics.css");
@import url("tokens/typography.css");

*, *::before, *::after { box-sizing: border-box; }
body { margin: 0; background: var(--color-bg); color: var(--color-text); font-family: var(--font-medium); font-size: var(--font-size-body); }

/* Glass panel: blur + translucent fill + 1px border. All three are mandatory. */
.glass {
  background: var(--color-surface);
  border: var(--layout-border-width) solid var(--color-surface-border);
  -webkit-backdrop-filter: blur(var(--blur-panel));
  backdrop-filter: blur(var(--blur-panel));
}
.glass--strong { background: var(--color-surface-strong); }
`);

// guidelines + README
cpSync("design/tokens.md", join(OUT, "guidelines/tokens.md"));
cpSync("design/README.md", join(OUT, "guidelines/README.md"));
for (const f of readdirSync("design/screens")) cpSync(join("design/screens", f), join(OUT, "guidelines/screens", f));

// spec digests: header + Problem / Goals / User stories / screen inventory (no ACs: those are for implementation)
mkdirSync(join(OUT, "guidelines/specs"), { recursive: true });
const KEEP = /^## (Проблем|Goals|User stories|Инвентарь)/;
let specIndex = "";
for (const f of readdirSync("specs").filter((n) => /^SPEC-\d+.*\.md$/.test(n)).sort()) {
  const lines = read(join("specs", f)).split("\n");
  const out = [];
  let keep = true; // header before the first "##"
  for (const l of lines) {
    if (l.startsWith("## ")) keep = KEEP.test(l);
    if (keep) out.push(l);
  }
  const title = lines[0].replace(/^# Spec:\s*/, "");
  writeFileSync(join(OUT, "guidelines/specs", f), `> Digest of specs/${f} (problem, goals/non-goals, user stories, screen inventory). Acceptance criteria and contracts are omitted; the full spec lives in the repo. Status in the header may be outdated.\n\n${out.join("\n")}\n`);
  specIndex += `- \`guidelines/specs/${f}\` — ${title}\n`;
}

// mockups: snapshot of the Claude Design canvas, refreshed manually (see NOTES.md)
const MSRC = ".design-sync/mockups-src/project";
let mockIndex = "";
try {
  const canvas = JSON.parse(read(join(MSRC, "canvas.json")));
  mkdirSync(join(OUT, "guidelines/mockups"), { recursive: true });
  for (const name of canvas.order) {
    cpSync(join(MSRC, name), join(OUT, "guidelines/mockups", name));
    mockIndex += `- \`${name}\` — ${canvas.boards[name]?.title ?? name}\n`;
  }
  writeFileSync(join(OUT, "guidelines/mockups/README.md"), `# Earlier mockups (reference snapshot)

Snapshot of the canvas "${canvas.title}" (16 artboards, 390x844). Use them for **screen structure, flow and copy** only.

**Do NOT copy their styling.** They predate the current rules and contain things that are now forbidden or replaced:
emoji flags, \`font-weight:600\`, gradient backgrounds, text glyphs (\`+\`, \`-\`) instead of Feather icons, hard-coded hex/px
values, and a per-mockup accent colour switcher. Where a mockup and \`README.md\` / \`guidelines/tokens.md\` disagree, the README
and tokens win; where a mockup and a \`guidelines/screens/*.md\` spec disagree, say so instead of silently picking one.
Files are Design Component source (\`.dc.html\`, \`{{holes}}\`, \`support.js\`): read them as text, do not try to run them.

${mockIndex}`);
} catch (e) { console.warn("no mockups snapshot:", e.message); }

const index = `\n\n## Token index (generated)\n\nColours (light | dark):\n\n| Token | Light | Dark |\n|---|---|---|\n${Object.keys(light).map((k) => `| \`--color-${kebab(k)}\` | \`${light[k]}\` | \`${dark[k]}\` |`).join("\n")}\n`;
const more = `\n\n## More reference in guidelines/\n\n- \`guidelines/mockups/README.md\` — earlier mockups (layout/flow only, NOT styling)\n- \`guidelines/specs/\` — product spec digests:\n${specIndex}`;
writeFileSync(join(OUT, "README.md"), read(".design-sync/conventions.md") + more + index);
console.log("built", OUT);
