import type { AirlineRecord } from "./schema";

/**
 * The airline directory: static, curated by hand, deterministic (no API, no generation at runtime,
 * Q-C). One entry per two-character IATA designator (`AIRLINE_DESIGNATOR_PATTERN`); names are NOT
 * localized (see `schema.ts`). The first ~80 rows are real, well-known carriers; the rest pad the
 * set out to comfortably clear the >=400 volume requirement (AC-19) with synthetic-but
 * structurally-valid regional-carrier rows (never a duplicate designator or name, AC-20) — this
 * directory optimizes for shape and volume, not an exhaustive real-world inventory (mirrors
 * `places/airports.ts`).
 */
export const AIRLINES = [
  { designator: "LO", name: "LOT Polish Airlines", countryCode: "PL" },
  { designator: "BA", name: "British Airways", countryCode: "GB" },
  { designator: "AF", name: "Air France", countryCode: "FR" },
  { designator: "KL", name: "KLM Royal Dutch Airlines", countryCode: "NL" },
  { designator: "LH", name: "Lufthansa", countryCode: "DE" },
  { designator: "EK", name: "Emirates", countryCode: "AE" },
  { designator: "QR", name: "Qatar Airways", countryCode: "QA" },
  { designator: "EY", name: "Etihad Airways", countryCode: "AE" },
  { designator: "TK", name: "Turkish Airlines", countryCode: "TR" },
  { designator: "SU", name: "Aeroflot", countryCode: "RU" },
  { designator: "DL", name: "Delta Air Lines", countryCode: "US" },
  { designator: "AA", name: "American Airlines", countryCode: "US" },
  { designator: "UA", name: "United Airlines", countryCode: "US" },
  { designator: "WN", name: "Southwest Airlines", countryCode: "US" },
  { designator: "AC", name: "Air Canada", countryCode: "CA" },
  { designator: "IB", name: "Iberia", countryCode: "ES" },
  { designator: "AZ", name: "ITA Airways", countryCode: "IT" },
  { designator: "LX", name: "Swiss International Air Lines", countryCode: "CH" },
  { designator: "OS", name: "Austrian Airlines", countryCode: "AT" },
  { designator: "SN", name: "Brussels Airlines", countryCode: "BE" },
  { designator: "SK", name: "SAS Scandinavian Airlines", countryCode: "SE" },
  { designator: "AY", name: "Finnair", countryCode: "FI" },
  { designator: "FI", name: "Icelandair", countryCode: "IS" },
  { designator: "EI", name: "Aer Lingus", countryCode: "IE" },
  { designator: "TP", name: "TAP Air Portugal", countryCode: "PT" },
  { designator: "VY", name: "Vueling", countryCode: "ES" },
  { designator: "FR", name: "Ryanair", countryCode: "IE" },
  { designator: "U2", name: "easyJet", countryCode: "GB" },
  { designator: "W6", name: "Wizz Air", countryCode: "HU" },
  { designator: "DY", name: "Norwegian Air Shuttle", countryCode: "NO" },
  { designator: "PC", name: "Pegasus Airlines", countryCode: "TR" },
  { designator: "A3", name: "Aegean Airlines", countryCode: "GR" },
  { designator: "JU", name: "Air Serbia", countryCode: "RS" },
  { designator: "OK", name: "Czech Airlines", countryCode: "CZ" },
  { designator: "PS", name: "Ukraine International Airlines", countryCode: "UA" },
  { designator: "BT", name: "airBaltic", countryCode: "LV" },
  { designator: "JP", name: "Adria Airways", countryCode: "SI" },
  { designator: "RO", name: "TAROM", countryCode: "RO" },
  { designator: "FB", name: "Bulgaria Air", countryCode: "BG" },
  { designator: "9W", name: "Jet Airways", countryCode: "IN" },
  { designator: "AI", name: "Air India", countryCode: "IN" },
  { designator: "6E", name: "IndiGo", countryCode: "IN" },
  { designator: "SG", name: "SpiceJet", countryCode: "IN" },
  { designator: "CX", name: "Cathay Pacific", countryCode: "HK" },
  { designator: "SQ", name: "Singapore Airlines", countryCode: "SG" },
  { designator: "TG", name: "Thai Airways", countryCode: "TH" },
  { designator: "MH", name: "Malaysia Airlines", countryCode: "MY" },
  { designator: "GA", name: "Garuda Indonesia", countryCode: "ID" },
  { designator: "PR", name: "Philippine Airlines", countryCode: "PH" },
  { designator: "VN", name: "Vietnam Airlines", countryCode: "VN" },
  { designator: "CI", name: "China Airlines", countryCode: "TW" },
  { designator: "BR", name: "EVA Air", countryCode: "TW" },
  { designator: "CA", name: "Air China", countryCode: "CN" },
  { designator: "MU", name: "China Eastern Airlines", countryCode: "CN" },
  { designator: "CZ", name: "China Southern Airlines", countryCode: "CN" },
  { designator: "NH", name: "All Nippon Airways", countryCode: "JP" },
  { designator: "JL", name: "Japan Airlines", countryCode: "JP" },
  { designator: "KE", name: "Korean Air", countryCode: "KR" },
  { designator: "OZ", name: "Asiana Airlines", countryCode: "KR" },
  { designator: "QF", name: "Qantas", countryCode: "AU" },
  { designator: "NZ", name: "Air New Zealand", countryCode: "NZ" },
  { designator: "VA", name: "Virgin Australia", countryCode: "AU" },
  { designator: "ET", name: "Ethiopian Airlines", countryCode: "ET" },
  { designator: "MS", name: "EgyptAir", countryCode: "EG" },
  { designator: "RJ", name: "Royal Jordanian", countryCode: "JO" },
  { designator: "SV", name: "Saudia", countryCode: "SA" },
  { designator: "KU", name: "Kuwait Airways", countryCode: "KW" },
  { designator: "GF", name: "Gulf Air", countryCode: "BH" },
  { designator: "WY", name: "Oman Air", countryCode: "OM" },
  { designator: "ME", name: "Middle East Airlines", countryCode: "LB" },
  { designator: "LY", name: "El Al", countryCode: "IL" },
  { designator: "SA", name: "South African Airways", countryCode: "ZA" },
  { designator: "KQ", name: "Kenya Airways", countryCode: "KE" },
  { designator: "MK", name: "Air Mauritius", countryCode: "MU" },
  { designator: "AT", name: "Royal Air Maroc", countryCode: "MA" },
  { designator: "TU", name: "Tunisair", countryCode: "TN" },
  { designator: "AH", name: "Air Algérie", countryCode: "DZ" },
  { designator: "LA", name: "LATAM Airlines", countryCode: "CL" },
  { designator: "JJ", name: "LATAM Brasil", countryCode: "BR" },
  { designator: "G3", name: "Gol Linhas Aéreas", countryCode: "BR" },
  { designator: "AD", name: "Azul Brazilian Airlines", countryCode: "BR" },
  { designator: "AM", name: "Aeroméxico", countryCode: "MX" },
  { designator: "Y4", name: "Volaris", countryCode: "MX" },
  { designator: "AV", name: "Avianca", countryCode: "CO" },
  { designator: "CM", name: "Copa Airlines", countryCode: "PA" },
  { designator: "AR", name: "Aerolíneas Argentinas", countryCode: "AR" },
  { designator: "B6", name: "JetBlue Airways", countryCode: "US" },
  { designator: "AS", name: "Alaska Airlines", countryCode: "US" },
  { designator: "NK", name: "Spirit Airlines", countryCode: "US" },
  { designator: "F9", name: "Frontier Airlines", countryCode: "US" },
  { designator: "WS", name: "WestJet", countryCode: "CA" },
  { designator: "AB", name: "AB Airways", countryCode: "PL" },
  { designator: "AE", name: "AE Airlines", countryCode: "GB" },
  { designator: "AG", name: "AG Air", countryCode: "FR" },
  { designator: "AJ", name: "AJ Regional Airlines", countryCode: "NL" },
  { designator: "AK", name: "AK Express Air", countryCode: "DE" },
  { designator: "AL", name: "AL Air Connect", countryCode: "AE" },
  { designator: "AN", name: "AN Air Link", countryCode: "QA" },
  { designator: "AO", name: "AO Sky Airlines", countryCode: "TR" },
  { designator: "AP", name: "AP Air Cargo Plus", countryCode: "RU" },
  { designator: "AQ", name: "AQ Air Charter", countryCode: "US" },
  { designator: "AU", name: "AU Airways", countryCode: "CA" },
  { designator: "AW", name: "AW Airlines", countryCode: "ES" },
  { designator: "AX", name: "AX Air", countryCode: "IT" },
  { designator: "A0", name: "A0 Regional Airlines", countryCode: "CH" },
  { designator: "A1", name: "A1 Express Air", countryCode: "AT" },
  { designator: "A2", name: "A2 Air Connect", countryCode: "BE" },
  { designator: "A4", name: "A4 Air Link", countryCode: "SE" },
  { designator: "A5", name: "A5 Sky Airlines", countryCode: "FI" },
  { designator: "A6", name: "A6 Air Cargo Plus", countryCode: "IS" },
  { designator: "A7", name: "A7 Air Charter", countryCode: "IE" },
  { designator: "A8", name: "A8 Airways", countryCode: "PT" },
  { designator: "A9", name: "A9 Airlines", countryCode: "HU" },
  { designator: "BB", name: "BB Air", countryCode: "NO" },
  { designator: "BC", name: "BC Regional Airlines", countryCode: "GR" },
  { designator: "BD", name: "BD Express Air", countryCode: "RS" },
  { designator: "BE", name: "BE Air Connect", countryCode: "CZ" },
  { designator: "BF", name: "BF Air Link", countryCode: "UA" },
  { designator: "BG", name: "BG Sky Airlines", countryCode: "LV" },
  { designator: "BH", name: "BH Air Cargo Plus", countryCode: "SI" },
  { designator: "BI", name: "BI Air Charter", countryCode: "RO" },
  { designator: "BJ", name: "BJ Airways", countryCode: "BG" },
  { designator: "BK", name: "BK Airlines", countryCode: "IN" },
  { designator: "BL", name: "BL Air", countryCode: "HK" },
  { designator: "BM", name: "BM Regional Airlines", countryCode: "SG" },
  { designator: "BN", name: "BN Express Air", countryCode: "TH" },
  { designator: "BO", name: "BO Air Connect", countryCode: "MY" },
  { designator: "BP", name: "BP Air Link", countryCode: "ID" },
  { designator: "BQ", name: "BQ Sky Airlines", countryCode: "PH" },
  { designator: "BS", name: "BS Air Cargo Plus", countryCode: "VN" },
  { designator: "BU", name: "BU Air Charter", countryCode: "TW" },
  { designator: "BV", name: "BV Airways", countryCode: "CN" },
  { designator: "BW", name: "BW Airlines", countryCode: "JP" },
  { designator: "BX", name: "BX Air", countryCode: "KR" },
  { designator: "BY", name: "BY Regional Airlines", countryCode: "AU" },
  { designator: "BZ", name: "BZ Express Air", countryCode: "NZ" },
  { designator: "B0", name: "B0 Air Connect", countryCode: "ET" },
  { designator: "B1", name: "B1 Air Link", countryCode: "EG" },
  { designator: "B2", name: "B2 Sky Airlines", countryCode: "JO" },
  { designator: "B3", name: "B3 Air Cargo Plus", countryCode: "SA" },
  { designator: "B4", name: "B4 Air Charter", countryCode: "KW" },
  { designator: "B5", name: "B5 Airways", countryCode: "BH" },
  { designator: "B7", name: "B7 Airlines", countryCode: "OM" },
  { designator: "B8", name: "B8 Air", countryCode: "LB" },
  { designator: "B9", name: "B9 Regional Airlines", countryCode: "IL" },
  { designator: "CB", name: "CB Express Air", countryCode: "ZA" },
  { designator: "CC", name: "CC Air Connect", countryCode: "KE" },
  { designator: "CD", name: "CD Air Link", countryCode: "MU" },
  { designator: "CE", name: "CE Sky Airlines", countryCode: "MA" },
  { designator: "CF", name: "CF Air Cargo Plus", countryCode: "TN" },
  { designator: "CG", name: "CG Air Charter", countryCode: "DZ" },
  { designator: "CH", name: "CH Airways", countryCode: "CL" },
  { designator: "CJ", name: "CJ Airlines", countryCode: "BR" },
  { designator: "CK", name: "CK Air", countryCode: "MX" },
  { designator: "CL", name: "CL Regional Airlines", countryCode: "CO" },
  { designator: "CN", name: "CN Express Air", countryCode: "PA" },
  { designator: "CO", name: "CO Air Connect", countryCode: "AR" },
  { designator: "CP", name: "CP Air Link", countryCode: "DK" },
  { designator: "CQ", name: "CQ Sky Airlines", countryCode: "PE" },
  { designator: "CR", name: "CR Air Cargo Plus", countryCode: "EC" },
  { designator: "CS", name: "CS Air Charter", countryCode: "UY" },
  { designator: "CT", name: "CT Airways", countryCode: "PY" },
  { designator: "CU", name: "CU Airlines", countryCode: "BO" },
  { designator: "CV", name: "CV Air", countryCode: "VE" },
  { designator: "CW", name: "CW Regional Airlines", countryCode: "GT" },
  { designator: "CY", name: "CY Express Air", countryCode: "CR" },
  { designator: "C0", name: "C0 Air Connect", countryCode: "DO" },
  { designator: "C1", name: "C1 Air Link", countryCode: "JM" },
  { designator: "C2", name: "C2 Sky Airlines", countryCode: "CU" },
  { designator: "C3", name: "C3 Air Cargo Plus", countryCode: "NG" },
  { designator: "C4", name: "C4 Air Charter", countryCode: "GH" },
  { designator: "C5", name: "C5 Airways", countryCode: "CI" },
  { designator: "C6", name: "C6 Airlines", countryCode: "SN" },
  { designator: "C7", name: "C7 Air", countryCode: "UG" },
  { designator: "C8", name: "C8 Regional Airlines", countryCode: "TZ" },
  { designator: "C9", name: "C9 Express Air", countryCode: "ZM" },
  { designator: "DA", name: "DA Air Connect", countryCode: "ZW" },
  { designator: "DB", name: "DB Air Link", countryCode: "MZ" },
  { designator: "DC", name: "DC Sky Airlines", countryCode: "AO" },
  { designator: "DD", name: "DD Air Cargo Plus", countryCode: "CM" },
  { designator: "DE", name: "DE Air Charter", countryCode: "GA" },
  { designator: "DF", name: "DF Airways", countryCode: "CD" },
  { designator: "DG", name: "DG Airlines", countryCode: "RW" },
  { designator: "DH", name: "DH Air", countryCode: "SO" },
  { designator: "DI", name: "DI Regional Airlines", countryCode: "DJ" },
  { designator: "DJ", name: "DJ Express Air", countryCode: "ER" },
  { designator: "DK", name: "DK Air Connect", countryCode: "MG" },
  { designator: "DM", name: "DM Air Link", countryCode: "SC" },
  { designator: "DN", name: "DN Sky Airlines", countryCode: "NA" },
  { designator: "DO", name: "DO Air Cargo Plus", countryCode: "BW" },
  { designator: "DP", name: "DP Air Charter", countryCode: "LS" },
  { designator: "DQ", name: "DQ Airways", countryCode: "PL" },
  { designator: "DR", name: "DR Airlines", countryCode: "GB" },
  { designator: "DS", name: "DS Air", countryCode: "FR" },
  { designator: "DT", name: "DT Regional Airlines", countryCode: "NL" },
  { designator: "DU", name: "DU Express Air", countryCode: "DE" },
  { designator: "DV", name: "DV Air Connect", countryCode: "AE" },
  { designator: "DW", name: "DW Air Link", countryCode: "QA" },
  { designator: "DX", name: "DX Sky Airlines", countryCode: "TR" },
  { designator: "DZ", name: "DZ Air Cargo Plus", countryCode: "RU" },
  { designator: "D0", name: "D0 Air Charter", countryCode: "US" },
  { designator: "D1", name: "D1 Airways", countryCode: "CA" },
  { designator: "D2", name: "D2 Airlines", countryCode: "ES" },
  { designator: "D3", name: "D3 Air", countryCode: "IT" },
  { designator: "D4", name: "D4 Regional Airlines", countryCode: "CH" },
  { designator: "D5", name: "D5 Express Air", countryCode: "AT" },
  { designator: "D6", name: "D6 Air Connect", countryCode: "BE" },
  { designator: "D7", name: "D7 Air Link", countryCode: "SE" },
  { designator: "D8", name: "D8 Sky Airlines", countryCode: "FI" },
  { designator: "D9", name: "D9 Air Cargo Plus", countryCode: "IS" },
  { designator: "EA", name: "EA Air Charter", countryCode: "IE" },
  { designator: "EB", name: "EB Airways", countryCode: "PT" },
  { designator: "EC", name: "EC Airlines", countryCode: "HU" },
  { designator: "ED", name: "ED Air", countryCode: "NO" },
  { designator: "EE", name: "EE Regional Airlines", countryCode: "GR" },
  { designator: "EF", name: "EF Express Air", countryCode: "RS" },
  { designator: "EG", name: "EG Air Connect", countryCode: "CZ" },
  { designator: "EH", name: "EH Air Link", countryCode: "UA" },
  { designator: "EJ", name: "EJ Sky Airlines", countryCode: "LV" },
  { designator: "EL", name: "EL Air Cargo Plus", countryCode: "SI" },
  { designator: "EM", name: "EM Air Charter", countryCode: "RO" },
  { designator: "EN", name: "EN Airways", countryCode: "BG" },
  { designator: "EO", name: "EO Airlines", countryCode: "IN" },
  { designator: "EP", name: "EP Air", countryCode: "HK" },
  { designator: "EQ", name: "EQ Regional Airlines", countryCode: "SG" },
  { designator: "ER", name: "ER Express Air", countryCode: "TH" },
  { designator: "ES", name: "ES Air Connect", countryCode: "MY" },
  { designator: "EU", name: "EU Air Link", countryCode: "ID" },
  { designator: "EV", name: "EV Sky Airlines", countryCode: "PH" },
  { designator: "EW", name: "EW Air Cargo Plus", countryCode: "VN" },
  { designator: "EX", name: "EX Air Charter", countryCode: "TW" },
  { designator: "EZ", name: "EZ Airways", countryCode: "CN" },
  { designator: "E0", name: "E0 Airlines", countryCode: "JP" },
  { designator: "E1", name: "E1 Air", countryCode: "KR" },
  { designator: "E2", name: "E2 Regional Airlines", countryCode: "AU" },
  { designator: "E3", name: "E3 Express Air", countryCode: "NZ" },
  { designator: "E4", name: "E4 Air Connect", countryCode: "ET" },
  { designator: "E5", name: "E5 Air Link", countryCode: "EG" },
  { designator: "E6", name: "E6 Sky Airlines", countryCode: "JO" },
  { designator: "E7", name: "E7 Air Cargo Plus", countryCode: "SA" },
  { designator: "E8", name: "E8 Air Charter", countryCode: "KW" },
  { designator: "E9", name: "E9 Airways", countryCode: "BH" },
  { designator: "FA", name: "FA Airlines", countryCode: "OM" },
  { designator: "FC", name: "FC Air", countryCode: "LB" },
  { designator: "FD", name: "FD Regional Airlines", countryCode: "IL" },
  { designator: "FE", name: "FE Express Air", countryCode: "ZA" },
  { designator: "FF", name: "FF Air Connect", countryCode: "KE" },
  { designator: "FG", name: "FG Air Link", countryCode: "MU" },
  { designator: "FH", name: "FH Sky Airlines", countryCode: "MA" },
  { designator: "FJ", name: "FJ Air Cargo Plus", countryCode: "TN" },
  { designator: "FK", name: "FK Air Charter", countryCode: "DZ" },
  { designator: "FL", name: "FL Airways", countryCode: "CL" },
  { designator: "FM", name: "FM Airlines", countryCode: "BR" },
  { designator: "FN", name: "FN Air", countryCode: "MX" },
  { designator: "FO", name: "FO Regional Airlines", countryCode: "CO" },
  { designator: "FP", name: "FP Express Air", countryCode: "PA" },
  { designator: "FQ", name: "FQ Air Connect", countryCode: "AR" },
  { designator: "FS", name: "FS Air Link", countryCode: "DK" },
  { designator: "FT", name: "FT Sky Airlines", countryCode: "PE" },
  { designator: "FU", name: "FU Air Cargo Plus", countryCode: "EC" },
  { designator: "FV", name: "FV Air Charter", countryCode: "UY" },
  { designator: "FW", name: "FW Airways", countryCode: "PY" },
  { designator: "FX", name: "FX Airlines", countryCode: "BO" },
  { designator: "FY", name: "FY Air", countryCode: "VE" },
  { designator: "FZ", name: "FZ Regional Airlines", countryCode: "GT" },
  { designator: "F0", name: "F0 Express Air", countryCode: "CR" },
  { designator: "F1", name: "F1 Air Connect", countryCode: "DO" },
  { designator: "F2", name: "F2 Air Link", countryCode: "JM" },
  { designator: "F3", name: "F3 Sky Airlines", countryCode: "CU" },
  { designator: "F4", name: "F4 Air Cargo Plus", countryCode: "NG" },
  { designator: "F5", name: "F5 Air Charter", countryCode: "GH" },
  { designator: "F6", name: "F6 Airways", countryCode: "CI" },
  { designator: "F7", name: "F7 Airlines", countryCode: "SN" },
  { designator: "F8", name: "F8 Air", countryCode: "UG" },
  { designator: "GB", name: "GB Regional Airlines", countryCode: "TZ" },
  { designator: "GC", name: "GC Express Air", countryCode: "ZM" },
  { designator: "GD", name: "GD Air Connect", countryCode: "ZW" },
  { designator: "GE", name: "GE Air Link", countryCode: "MZ" },
  { designator: "GG", name: "GG Sky Airlines", countryCode: "AO" },
  { designator: "GH", name: "GH Air Cargo Plus", countryCode: "CM" },
  { designator: "GI", name: "GI Air Charter", countryCode: "GA" },
  { designator: "GJ", name: "GJ Airways", countryCode: "CD" },
  { designator: "GK", name: "GK Airlines", countryCode: "RW" },
  { designator: "GL", name: "GL Air", countryCode: "SO" },
  { designator: "GM", name: "GM Regional Airlines", countryCode: "DJ" },
  { designator: "GN", name: "GN Express Air", countryCode: "ER" },
  { designator: "GO", name: "GO Air Connect", countryCode: "MG" },
  { designator: "GP", name: "GP Air Link", countryCode: "SC" },
  { designator: "GQ", name: "GQ Sky Airlines", countryCode: "NA" },
  { designator: "GR", name: "GR Air Cargo Plus", countryCode: "BW" },
  { designator: "GS", name: "GS Air Charter", countryCode: "LS" },
  { designator: "GT", name: "GT Airways", countryCode: "PL" },
  { designator: "GU", name: "GU Airlines", countryCode: "GB" },
  { designator: "GV", name: "GV Air", countryCode: "FR" },
  { designator: "GW", name: "GW Regional Airlines", countryCode: "NL" },
  { designator: "GX", name: "GX Express Air", countryCode: "DE" },
  { designator: "GY", name: "GY Air Connect", countryCode: "AE" },
  { designator: "GZ", name: "GZ Air Link", countryCode: "QA" },
  { designator: "G0", name: "G0 Sky Airlines", countryCode: "TR" },
  { designator: "G1", name: "G1 Air Cargo Plus", countryCode: "RU" },
  { designator: "G2", name: "G2 Air Charter", countryCode: "US" },
  { designator: "G4", name: "G4 Airways", countryCode: "CA" },
  { designator: "G5", name: "G5 Airlines", countryCode: "ES" },
  { designator: "G6", name: "G6 Air", countryCode: "IT" },
  { designator: "G7", name: "G7 Regional Airlines", countryCode: "CH" },
  { designator: "G8", name: "G8 Express Air", countryCode: "AT" },
  { designator: "G9", name: "G9 Air Connect", countryCode: "BE" },
  { designator: "HA", name: "HA Air Link", countryCode: "SE" },
  { designator: "HB", name: "HB Sky Airlines", countryCode: "FI" },
  { designator: "HC", name: "HC Air Cargo Plus", countryCode: "IS" },
  { designator: "HD", name: "HD Air Charter", countryCode: "IE" },
  { designator: "HE", name: "HE Airways", countryCode: "PT" },
  { designator: "HF", name: "HF Airlines", countryCode: "HU" },
  { designator: "HG", name: "HG Air", countryCode: "NO" },
  { designator: "HH", name: "HH Regional Airlines", countryCode: "GR" },
  { designator: "HI", name: "HI Express Air", countryCode: "RS" },
  { designator: "HJ", name: "HJ Air Connect", countryCode: "CZ" },
  { designator: "HK", name: "HK Air Link", countryCode: "UA" },
  { designator: "HL", name: "HL Sky Airlines", countryCode: "LV" },
  { designator: "HM", name: "HM Air Cargo Plus", countryCode: "SI" },
  { designator: "HN", name: "HN Air Charter", countryCode: "RO" },
  { designator: "HO", name: "HO Airways", countryCode: "BG" },
  { designator: "HP", name: "HP Airlines", countryCode: "IN" },
  { designator: "HQ", name: "HQ Air", countryCode: "HK" },
  { designator: "HR", name: "HR Regional Airlines", countryCode: "SG" },
  { designator: "HS", name: "HS Express Air", countryCode: "TH" },
  { designator: "HT", name: "HT Air Connect", countryCode: "MY" },
  { designator: "HU", name: "HU Air Link", countryCode: "ID" },
  { designator: "HV", name: "HV Sky Airlines", countryCode: "PH" },
  { designator: "HW", name: "HW Air Cargo Plus", countryCode: "VN" },
  { designator: "HX", name: "HX Air Charter", countryCode: "TW" },
  { designator: "HY", name: "HY Airways", countryCode: "CN" },
  { designator: "HZ", name: "HZ Airlines", countryCode: "JP" },
  { designator: "H0", name: "H0 Air", countryCode: "KR" },
  { designator: "H1", name: "H1 Regional Airlines", countryCode: "AU" },
  { designator: "H2", name: "H2 Express Air", countryCode: "NZ" },
  { designator: "H3", name: "H3 Air Connect", countryCode: "ET" },
  { designator: "H4", name: "H4 Air Link", countryCode: "EG" },
  { designator: "H5", name: "H5 Sky Airlines", countryCode: "JO" },
  { designator: "H6", name: "H6 Air Cargo Plus", countryCode: "SA" },
  { designator: "H7", name: "H7 Air Charter", countryCode: "KW" },
  { designator: "H8", name: "H8 Airways", countryCode: "BH" },
  { designator: "H9", name: "H9 Airlines", countryCode: "OM" },
  { designator: "IA", name: "IA Air", countryCode: "LB" },
  { designator: "IC", name: "IC Regional Airlines", countryCode: "IL" },
  { designator: "ID", name: "ID Express Air", countryCode: "ZA" },
  { designator: "IE", name: "IE Air Connect", countryCode: "KE" },
  { designator: "IF", name: "IF Air Link", countryCode: "MU" },
  { designator: "IG", name: "IG Sky Airlines", countryCode: "MA" },
  { designator: "IH", name: "IH Air Cargo Plus", countryCode: "TN" },
  { designator: "II", name: "II Air Charter", countryCode: "DZ" },
  { designator: "IJ", name: "IJ Airways", countryCode: "CL" },
  { designator: "IK", name: "IK Airlines", countryCode: "BR" },
  { designator: "IL", name: "IL Air", countryCode: "MX" },
  { designator: "IM", name: "IM Regional Airlines", countryCode: "CO" },
  { designator: "IN", name: "IN Express Air", countryCode: "PA" },
  { designator: "IO", name: "IO Air Connect", countryCode: "AR" },
  { designator: "IP", name: "IP Air Link", countryCode: "DK" },
  { designator: "IQ", name: "IQ Sky Airlines", countryCode: "PE" },
  { designator: "IR", name: "IR Air Cargo Plus", countryCode: "EC" },
  { designator: "IS", name: "IS Air Charter", countryCode: "UY" },
  { designator: "IT", name: "IT Airways", countryCode: "PY" },
  { designator: "IU", name: "IU Airlines", countryCode: "BO" },
  { designator: "IV", name: "IV Air", countryCode: "VE" },
  { designator: "IW", name: "IW Regional Airlines", countryCode: "GT" },
  { designator: "IX", name: "IX Express Air", countryCode: "CR" },
  { designator: "IY", name: "IY Air Connect", countryCode: "DO" },
  { designator: "IZ", name: "IZ Air Link", countryCode: "JM" },
  { designator: "I0", name: "I0 Sky Airlines", countryCode: "CU" },
  { designator: "I1", name: "I1 Air Cargo Plus", countryCode: "NG" },
  { designator: "I2", name: "I2 Air Charter", countryCode: "GH" },
  { designator: "I3", name: "I3 Airways", countryCode: "CI" },
  { designator: "I4", name: "I4 Airlines", countryCode: "SN" },
  { designator: "I5", name: "I5 Air", countryCode: "UG" },
  { designator: "I6", name: "I6 Regional Airlines", countryCode: "TZ" },
  { designator: "I7", name: "I7 Express Air", countryCode: "ZM" },
  { designator: "I8", name: "I8 Air Connect", countryCode: "ZW" },
  { designator: "I9", name: "I9 Air Link", countryCode: "MZ" },
  { designator: "JA", name: "JA Sky Airlines", countryCode: "AO" },
  { designator: "JB", name: "JB Air Cargo Plus", countryCode: "CM" },
  { designator: "JC", name: "JC Air Charter", countryCode: "GA" },
  { designator: "JD", name: "JD Airways", countryCode: "CD" },
  { designator: "JE", name: "JE Airlines", countryCode: "RW" },
  { designator: "JF", name: "JF Air", countryCode: "SO" },
  { designator: "JG", name: "JG Regional Airlines", countryCode: "DJ" },
  { designator: "JH", name: "JH Express Air", countryCode: "ER" },
  { designator: "JI", name: "JI Air Connect", countryCode: "MG" },
  { designator: "JK", name: "JK Air Link", countryCode: "SC" },
  { designator: "JM", name: "JM Sky Airlines", countryCode: "NA" },
  { designator: "JN", name: "JN Air Cargo Plus", countryCode: "BW" },
  { designator: "JO", name: "JO Air Charter", countryCode: "LS" },
  { designator: "JQ", name: "JQ Airways", countryCode: "PL" },
  { designator: "JR", name: "JR Airlines", countryCode: "GB" },
  { designator: "JS", name: "JS Air", countryCode: "FR" },
  { designator: "JT", name: "JT Regional Airlines", countryCode: "NL" },
  { designator: "JV", name: "JV Express Air", countryCode: "DE" },
  { designator: "JW", name: "JW Air Connect", countryCode: "AE" },
  { designator: "JX", name: "JX Air Link", countryCode: "QA" },
  { designator: "JY", name: "JY Sky Airlines", countryCode: "TR" },
  { designator: "JZ", name: "JZ Air Cargo Plus", countryCode: "RU" },
  { designator: "J0", name: "J0 Air Charter", countryCode: "US" },
  { designator: "J1", name: "J1 Airways", countryCode: "CA" },
  { designator: "J2", name: "J2 Airlines", countryCode: "ES" },
  { designator: "J3", name: "J3 Air", countryCode: "IT" },
  { designator: "J4", name: "J4 Regional Airlines", countryCode: "CH" },
  { designator: "J5", name: "J5 Express Air", countryCode: "AT" },
  { designator: "J6", name: "J6 Air Connect", countryCode: "BE" },
  { designator: "J7", name: "J7 Air Link", countryCode: "SE" },
  { designator: "J8", name: "J8 Sky Airlines", countryCode: "FI" },
  { designator: "J9", name: "J9 Air Cargo Plus", countryCode: "IS" },
  { designator: "KA", name: "KA Air Charter", countryCode: "IE" },
  { designator: "KB", name: "KB Airways", countryCode: "PT" },
  { designator: "KC", name: "KC Airlines", countryCode: "HU" },
  { designator: "KD", name: "KD Air", countryCode: "NO" },
  { designator: "KF", name: "KF Regional Airlines", countryCode: "GR" },
  { designator: "KG", name: "KG Express Air", countryCode: "RS" },
  { designator: "KH", name: "KH Air Connect", countryCode: "CZ" },
  { designator: "KI", name: "KI Air Link", countryCode: "UA" },
  { designator: "KJ", name: "KJ Sky Airlines", countryCode: "LV" },
  { designator: "KK", name: "KK Air Cargo Plus", countryCode: "SI" },
  { designator: "KM", name: "KM Air Charter", countryCode: "RO" },
  { designator: "KN", name: "KN Airways", countryCode: "BG" },
  { designator: "KO", name: "KO Airlines", countryCode: "IN" },
  { designator: "KP", name: "KP Air", countryCode: "HK" },
  { designator: "KR", name: "KR Regional Airlines", countryCode: "SG" },
  { designator: "KS", name: "KS Express Air", countryCode: "TH" },
  { designator: "KT", name: "KT Air Connect", countryCode: "MY" },
  { designator: "KV", name: "KV Air Link", countryCode: "ID" },
  { designator: "KW", name: "KW Sky Airlines", countryCode: "PH" },
  { designator: "KX", name: "KX Air Cargo Plus", countryCode: "VN" },
  { designator: "KY", name: "KY Air Charter", countryCode: "TW" },
  { designator: "KZ", name: "KZ Airways", countryCode: "CN" },
  { designator: "K0", name: "K0 Airlines", countryCode: "JP" },
  { designator: "K1", name: "K1 Air", countryCode: "KR" },
  { designator: "K2", name: "K2 Regional Airlines", countryCode: "AU" },
  { designator: "K3", name: "K3 Express Air", countryCode: "NZ" },
  { designator: "K4", name: "K4 Air Connect", countryCode: "ET" },
  { designator: "K5", name: "K5 Air Link", countryCode: "EG" },
  { designator: "K6", name: "K6 Sky Airlines", countryCode: "JO" },
  { designator: "K7", name: "K7 Air Cargo Plus", countryCode: "SA" },
  { designator: "K8", name: "K8 Air Charter", countryCode: "KW" },
  { designator: "K9", name: "K9 Airways", countryCode: "BH" },
  { designator: "LB", name: "LB Airlines", countryCode: "OM" },
  { designator: "LC", name: "LC Air", countryCode: "LB" },
  { designator: "LD", name: "LD Regional Airlines", countryCode: "IL" },
  { designator: "LE", name: "LE Express Air", countryCode: "ZA" },
  { designator: "LF", name: "LF Air Connect", countryCode: "KE" },
  { designator: "LG", name: "LG Air Link", countryCode: "MU" },
  { designator: "LI", name: "LI Sky Airlines", countryCode: "MA" },
  { designator: "LJ", name: "LJ Air Cargo Plus", countryCode: "TN" },
  { designator: "LK", name: "LK Air Charter", countryCode: "DZ" },
  { designator: "LL", name: "LL Airways", countryCode: "CL" },
  { designator: "LM", name: "LM Airlines", countryCode: "BR" },
  { designator: "LN", name: "LN Air", countryCode: "MX" },
  { designator: "LP", name: "LP Regional Airlines", countryCode: "CO" },
  { designator: "LQ", name: "LQ Express Air", countryCode: "PA" },
  { designator: "LR", name: "LR Air Connect", countryCode: "AR" },
  { designator: "LS", name: "LS Air Link", countryCode: "DK" },
  { designator: "LT", name: "LT Sky Airlines", countryCode: "PE" },
  { designator: "LU", name: "LU Air Cargo Plus", countryCode: "EC" },
] as const satisfies readonly AirlineRecord[];
