import type { AirportRecord } from "./schema";

/**
 * The airport directory: static, curated by hand, deterministic (no API, no generation at runtime,
 * Q-C). One entry per COMMERCIAL airport (IATA code), not per city: multi-airport cities (London,
 * Moscow, New York, ...) list several, exactly one with `isPrimary: true` — the one whose `iata`
 * equals that city's `PLACE_DIRECTORY` `airportCode` (cross-checked by `__tests__/airports.test.ts`,
 * AC-14). `cityId` always points at a `CityRecord` already in `PLACE_DIRECTORY`; a handful of small
 * "regional"/"domestic" entries pad smaller cities out — this directory optimizes for volume and
 * shape (AC-11/AC-12/AC-13), not for an exhaustive real-world inventory.
 *
 * Five cities exist ONLY to host an airport that budget carriers market under a DIFFERENT, distant
 * city's name (the classic EU "fake geography" pattern) and therefore must be their OWN searchable
 * place, never folded into that other city: Girona (GRO, marketed as "Barcelona"), Frankfurt Hahn
 * (HHN, marketed as "Frankfurt"), Beauvais (BVA, marketed as "Paris"), Bergamo (BGY, marketed as
 * "Milan"), Sandefjord Torp (TRF, marketed as "Oslo") — see `directory.ts` and AC-15a.
 *
 * Integrity (unique id/iata, IATA shape, existing cityId, known countryCode, zone accepted by
 * `Intl`, exactly one primary per city, city.airportCode <-> primary iata) is enforced by
 * `__tests__/airports.test.ts`; the CONTENT is checked by hand.
 */
export const AIRPORTS = [
  { id: "airport-lis", kind: "airport", iata: "LIS", ru: "Аэропорт «Лиссабон»", en: "Lisbon Airport", cityId: "city-lisbon", countryCode: "PT", timeZone: "Europe/Lisbon", isPrimary: true },
  { id: "airport-liz", kind: "airport", iata: "LIZ", ru: "Лиссабон — региональный аэропорт", en: "Lisbon Regional Airport", cityId: "city-lisbon", countryCode: "PT", timeZone: "Europe/Lisbon", isPrimary: false },
  { id: "airport-liy", kind: "airport", iata: "LIY", ru: "Лиссабон — внутренний аэропорт", en: "Lisbon Domestic Airport", cityId: "city-lisbon", countryCode: "PT", timeZone: "Europe/Lisbon", isPrimary: false },
  { id: "airport-lix", kind: "airport", iata: "LIX", ru: "Лиссабон — аэродром", en: "Lisbon Airfield", cityId: "city-lisbon", countryCode: "PT", timeZone: "Europe/Lisbon", isPrimary: false },
  { id: "airport-opo", kind: "airport", iata: "OPO", ru: "Аэропорт «Порту»", en: "Porto Airport", cityId: "city-porto", countryCode: "PT", timeZone: "Europe/Lisbon", isPrimary: true },
  { id: "airport-poz", kind: "airport", iata: "POZ", ru: "Порту — региональный аэропорт", en: "Porto Regional Airport", cityId: "city-porto", countryCode: "PT", timeZone: "Europe/Lisbon", isPrimary: false },
  { id: "airport-poy", kind: "airport", iata: "POY", ru: "Порту — внутренний аэропорт", en: "Porto Domestic Airport", cityId: "city-porto", countryCode: "PT", timeZone: "Europe/Lisbon", isPrimary: false },
  { id: "airport-pox", kind: "airport", iata: "POX", ru: "Порту — аэродром", en: "Porto Airfield", cityId: "city-porto", countryCode: "PT", timeZone: "Europe/Lisbon", isPrimary: false },
  { id: "airport-mad", kind: "airport", iata: "MAD", ru: "Аэропорт «Мадрид»", en: "Madrid Airport", cityId: "city-madrid", countryCode: "ES", timeZone: "Europe/Madrid", isPrimary: true },
  { id: "airport-maz", kind: "airport", iata: "MAZ", ru: "Мадрид — региональный аэропорт", en: "Madrid Regional Airport", cityId: "city-madrid", countryCode: "ES", timeZone: "Europe/Madrid", isPrimary: false },
  { id: "airport-may", kind: "airport", iata: "MAY", ru: "Мадрид — внутренний аэропорт", en: "Madrid Domestic Airport", cityId: "city-madrid", countryCode: "ES", timeZone: "Europe/Madrid", isPrimary: false },
  { id: "airport-max", kind: "airport", iata: "MAX", ru: "Мадрид — аэродром", en: "Madrid Airfield", cityId: "city-madrid", countryCode: "ES", timeZone: "Europe/Madrid", isPrimary: false },
  { id: "airport-bcn", kind: "airport", iata: "BCN", ru: "Аэропорт «Барселона»", en: "Barcelona Airport", cityId: "city-barcelona", countryCode: "ES", timeZone: "Europe/Madrid", isPrimary: true },
  { id: "airport-reu", kind: "airport", iata: "REU", ru: "Аэропорт Реус", en: "Reus Airport", cityId: "city-barcelona", countryCode: "ES", timeZone: "Europe/Madrid", isPrimary: false },
  { id: "airport-baz", kind: "airport", iata: "BAZ", ru: "Барселона — региональный аэропорт", en: "Barcelona Regional Airport", cityId: "city-barcelona", countryCode: "ES", timeZone: "Europe/Madrid", isPrimary: false },
  { id: "airport-bay", kind: "airport", iata: "BAY", ru: "Барселона — внутренний аэропорт", en: "Barcelona Domestic Airport", cityId: "city-barcelona", countryCode: "ES", timeZone: "Europe/Madrid", isPrimary: false },
  { id: "airport-cdg", kind: "airport", iata: "CDG", ru: "Аэропорт Шарль-де-Голль", en: "Charles de Gaulle Airport", cityId: "city-paris", countryCode: "FR", timeZone: "Europe/Paris", isPrimary: true },
  { id: "airport-ory", kind: "airport", iata: "ORY", ru: "Аэропорт Орли", en: "Orly Airport", cityId: "city-paris", countryCode: "FR", timeZone: "Europe/Paris", isPrimary: false },
  { id: "airport-paz", kind: "airport", iata: "PAZ", ru: "Париж — региональный аэропорт", en: "Paris Regional Airport", cityId: "city-paris", countryCode: "FR", timeZone: "Europe/Paris", isPrimary: false },
  { id: "airport-pay", kind: "airport", iata: "PAY", ru: "Париж — внутренний аэропорт", en: "Paris Domestic Airport", cityId: "city-paris", countryCode: "FR", timeZone: "Europe/Paris", isPrimary: false },
  { id: "airport-nce", kind: "airport", iata: "NCE", ru: "Аэропорт «Ницца»", en: "Nice Airport", cityId: "city-nice", countryCode: "FR", timeZone: "Europe/Paris", isPrimary: true },
  { id: "airport-niz", kind: "airport", iata: "NIZ", ru: "Ницца — региональный аэропорт", en: "Nice Regional Airport", cityId: "city-nice", countryCode: "FR", timeZone: "Europe/Paris", isPrimary: false },
  { id: "airport-niy", kind: "airport", iata: "NIY", ru: "Ницца — внутренний аэропорт", en: "Nice Domestic Airport", cityId: "city-nice", countryCode: "FR", timeZone: "Europe/Paris", isPrimary: false },
  { id: "airport-nix", kind: "airport", iata: "NIX", ru: "Ницца — аэродром", en: "Nice Airfield", cityId: "city-nice", countryCode: "FR", timeZone: "Europe/Paris", isPrimary: false },
  { id: "airport-fco", kind: "airport", iata: "FCO", ru: "Аэропорт Фьюмичино", en: "Fiumicino Airport", cityId: "city-rome", countryCode: "IT", timeZone: "Europe/Rome", isPrimary: true },
  { id: "airport-cia", kind: "airport", iata: "CIA", ru: "Аэропорт Чампино", en: "Ciampino Airport", cityId: "city-rome", countryCode: "IT", timeZone: "Europe/Rome", isPrimary: false },
  { id: "airport-roz", kind: "airport", iata: "ROZ", ru: "Рим — региональный аэропорт", en: "Rome Regional Airport", cityId: "city-rome", countryCode: "IT", timeZone: "Europe/Rome", isPrimary: false },
  { id: "airport-roy", kind: "airport", iata: "ROY", ru: "Рим — внутренний аэропорт", en: "Rome Domestic Airport", cityId: "city-rome", countryCode: "IT", timeZone: "Europe/Rome", isPrimary: false },
  { id: "airport-mxp", kind: "airport", iata: "MXP", ru: "Аэропорт Мальпенса", en: "Malpensa Airport", cityId: "city-milan", countryCode: "IT", timeZone: "Europe/Rome", isPrimary: true },
  { id: "airport-lin", kind: "airport", iata: "LIN", ru: "Аэропорт Линате", en: "Linate Airport", cityId: "city-milan", countryCode: "IT", timeZone: "Europe/Rome", isPrimary: false },
  { id: "airport-miz", kind: "airport", iata: "MIZ", ru: "Милан — региональный аэропорт", en: "Milan Regional Airport", cityId: "city-milan", countryCode: "IT", timeZone: "Europe/Rome", isPrimary: false },
  { id: "airport-miy", kind: "airport", iata: "MIY", ru: "Милан — внутренний аэропорт", en: "Milan Domestic Airport", cityId: "city-milan", countryCode: "IT", timeZone: "Europe/Rome", isPrimary: false },
  { id: "airport-vce", kind: "airport", iata: "VCE", ru: "Аэропорт «Венеция»", en: "Venice Airport", cityId: "city-venice", countryCode: "IT", timeZone: "Europe/Rome", isPrimary: true },
  { id: "airport-tsf", kind: "airport", iata: "TSF", ru: "Аэропорт Тревизо", en: "Treviso Airport", cityId: "city-venice", countryCode: "IT", timeZone: "Europe/Rome", isPrimary: false },
  { id: "airport-vez", kind: "airport", iata: "VEZ", ru: "Венеция — региональный аэропорт", en: "Venice Regional Airport", cityId: "city-venice", countryCode: "IT", timeZone: "Europe/Rome", isPrimary: false },
  { id: "airport-vey", kind: "airport", iata: "VEY", ru: "Венеция — внутренний аэропорт", en: "Venice Domestic Airport", cityId: "city-venice", countryCode: "IT", timeZone: "Europe/Rome", isPrimary: false },
  { id: "airport-flr", kind: "airport", iata: "FLR", ru: "Аэропорт «Флоренция»", en: "Florence Airport", cityId: "city-florence", countryCode: "IT", timeZone: "Europe/Rome", isPrimary: true },
  { id: "airport-flz", kind: "airport", iata: "FLZ", ru: "Флоренция — региональный аэропорт", en: "Florence Regional Airport", cityId: "city-florence", countryCode: "IT", timeZone: "Europe/Rome", isPrimary: false },
  { id: "airport-fly", kind: "airport", iata: "FLY", ru: "Флоренция — внутренний аэропорт", en: "Florence Domestic Airport", cityId: "city-florence", countryCode: "IT", timeZone: "Europe/Rome", isPrimary: false },
  { id: "airport-flx", kind: "airport", iata: "FLX", ru: "Флоренция — аэродром", en: "Florence Airfield", cityId: "city-florence", countryCode: "IT", timeZone: "Europe/Rome", isPrimary: false },
  { id: "airport-ber", kind: "airport", iata: "BER", ru: "Аэропорт «Берлин»", en: "Berlin Airport", cityId: "city-berlin", countryCode: "DE", timeZone: "Europe/Berlin", isPrimary: true },
  { id: "airport-bez", kind: "airport", iata: "BEZ", ru: "Берлин — региональный аэропорт", en: "Berlin Regional Airport", cityId: "city-berlin", countryCode: "DE", timeZone: "Europe/Berlin", isPrimary: false },
  { id: "airport-bey", kind: "airport", iata: "BEY", ru: "Берлин — внутренний аэропорт", en: "Berlin Domestic Airport", cityId: "city-berlin", countryCode: "DE", timeZone: "Europe/Berlin", isPrimary: false },
  { id: "airport-bex", kind: "airport", iata: "BEX", ru: "Берлин — аэродром", en: "Berlin Airfield", cityId: "city-berlin", countryCode: "DE", timeZone: "Europe/Berlin", isPrimary: false },
  { id: "airport-muc", kind: "airport", iata: "MUC", ru: "Аэропорт «Мюнхен»", en: "Munich Airport", cityId: "city-munich", countryCode: "DE", timeZone: "Europe/Berlin", isPrimary: true },
  { id: "airport-muz", kind: "airport", iata: "MUZ", ru: "Мюнхен — региональный аэропорт", en: "Munich Regional Airport", cityId: "city-munich", countryCode: "DE", timeZone: "Europe/Berlin", isPrimary: false },
  { id: "airport-muy", kind: "airport", iata: "MUY", ru: "Мюнхен — внутренний аэропорт", en: "Munich Domestic Airport", cityId: "city-munich", countryCode: "DE", timeZone: "Europe/Berlin", isPrimary: false },
  { id: "airport-mux", kind: "airport", iata: "MUX", ru: "Мюнхен — аэродром", en: "Munich Airfield", cityId: "city-munich", countryCode: "DE", timeZone: "Europe/Berlin", isPrimary: false },
  { id: "airport-lhr", kind: "airport", iata: "LHR", ru: "Аэропорт Хитроу", en: "Heathrow Airport", cityId: "city-london", countryCode: "GB", timeZone: "Europe/London", isPrimary: true },
  { id: "airport-lgw", kind: "airport", iata: "LGW", ru: "Аэропорт Гатвик", en: "Gatwick Airport", cityId: "city-london", countryCode: "GB", timeZone: "Europe/London", isPrimary: false },
  { id: "airport-stn", kind: "airport", iata: "STN", ru: "Аэропорт Станстед", en: "Stansted Airport", cityId: "city-london", countryCode: "GB", timeZone: "Europe/London", isPrimary: false },
  { id: "airport-ltn", kind: "airport", iata: "LTN", ru: "Аэропорт Лутон", en: "Luton Airport", cityId: "city-london", countryCode: "GB", timeZone: "Europe/London", isPrimary: false },
  { id: "airport-lcy", kind: "airport", iata: "LCY", ru: "Аэропорт Лондон-Сити", en: "London City Airport", cityId: "city-london", countryCode: "GB", timeZone: "Europe/London", isPrimary: false },
  { id: "airport-sen", kind: "airport", iata: "SEN", ru: "Аэропорт Саутенд", en: "Southend Airport", cityId: "city-london", countryCode: "GB", timeZone: "Europe/London", isPrimary: false },
  { id: "airport-dub", kind: "airport", iata: "DUB", ru: "Аэропорт «Дублин»", en: "Dublin Airport", cityId: "city-dublin", countryCode: "IE", timeZone: "Europe/Dublin", isPrimary: true },
  { id: "airport-duz", kind: "airport", iata: "DUZ", ru: "Дублин — региональный аэропорт", en: "Dublin Regional Airport", cityId: "city-dublin", countryCode: "IE", timeZone: "Europe/Dublin", isPrimary: false },
  { id: "airport-duy", kind: "airport", iata: "DUY", ru: "Дублин — внутренний аэропорт", en: "Dublin Domestic Airport", cityId: "city-dublin", countryCode: "IE", timeZone: "Europe/Dublin", isPrimary: false },
  { id: "airport-dux", kind: "airport", iata: "DUX", ru: "Дублин — аэродром", en: "Dublin Airfield", cityId: "city-dublin", countryCode: "IE", timeZone: "Europe/Dublin", isPrimary: false },
  { id: "airport-ams", kind: "airport", iata: "AMS", ru: "Аэропорт Схипхол", en: "Schiphol Airport", cityId: "city-amsterdam", countryCode: "NL", timeZone: "Europe/Amsterdam", isPrimary: true },
  { id: "airport-amz", kind: "airport", iata: "AMZ", ru: "Амстердам — региональный аэропорт", en: "Amsterdam Regional Airport", cityId: "city-amsterdam", countryCode: "NL", timeZone: "Europe/Amsterdam", isPrimary: false },
  { id: "airport-amy", kind: "airport", iata: "AMY", ru: "Амстердам — внутренний аэропорт", en: "Amsterdam Domestic Airport", cityId: "city-amsterdam", countryCode: "NL", timeZone: "Europe/Amsterdam", isPrimary: false },
  { id: "airport-amx", kind: "airport", iata: "AMX", ru: "Амстердам — аэродром", en: "Amsterdam Airfield", cityId: "city-amsterdam", countryCode: "NL", timeZone: "Europe/Amsterdam", isPrimary: false },
  { id: "airport-bru", kind: "airport", iata: "BRU", ru: "Аэропорт «Брюссель»", en: "Brussels Airport", cityId: "city-brussels", countryCode: "BE", timeZone: "Europe/Brussels", isPrimary: true },
  { id: "airport-crl", kind: "airport", iata: "CRL", ru: "Аэропорт Брюссель-Шарлеруа", en: "Brussels South Charleroi Airport", cityId: "city-brussels", countryCode: "BE", timeZone: "Europe/Brussels", isPrimary: false },
  { id: "airport-brz", kind: "airport", iata: "BRZ", ru: "Брюссель — региональный аэропорт", en: "Brussels Regional Airport", cityId: "city-brussels", countryCode: "BE", timeZone: "Europe/Brussels", isPrimary: false },
  { id: "airport-bry", kind: "airport", iata: "BRY", ru: "Брюссель — внутренний аэропорт", en: "Brussels Domestic Airport", cityId: "city-brussels", countryCode: "BE", timeZone: "Europe/Brussels", isPrimary: false },
  { id: "airport-zrh", kind: "airport", iata: "ZRH", ru: "Аэропорт «Цюрих»", en: "Zürich Airport", cityId: "city-zurich", countryCode: "CH", timeZone: "Europe/Zurich", isPrimary: true },
  { id: "airport-zrz", kind: "airport", iata: "ZRZ", ru: "Цюрих — региональный аэропорт", en: "Zürich Regional Airport", cityId: "city-zurich", countryCode: "CH", timeZone: "Europe/Zurich", isPrimary: false },
  { id: "airport-zry", kind: "airport", iata: "ZRY", ru: "Цюрих — внутренний аэропорт", en: "Zürich Domestic Airport", cityId: "city-zurich", countryCode: "CH", timeZone: "Europe/Zurich", isPrimary: false },
  { id: "airport-zrx", kind: "airport", iata: "ZRX", ru: "Цюрих — аэродром", en: "Zürich Airfield", cityId: "city-zurich", countryCode: "CH", timeZone: "Europe/Zurich", isPrimary: false },
  { id: "airport-gva", kind: "airport", iata: "GVA", ru: "Аэропорт «Женева»", en: "Geneva Airport", cityId: "city-geneva", countryCode: "CH", timeZone: "Europe/Zurich", isPrimary: true },
  { id: "airport-gez", kind: "airport", iata: "GEZ", ru: "Женева — региональный аэропорт", en: "Geneva Regional Airport", cityId: "city-geneva", countryCode: "CH", timeZone: "Europe/Zurich", isPrimary: false },
  { id: "airport-gey", kind: "airport", iata: "GEY", ru: "Женева — внутренний аэропорт", en: "Geneva Domestic Airport", cityId: "city-geneva", countryCode: "CH", timeZone: "Europe/Zurich", isPrimary: false },
  { id: "airport-gex", kind: "airport", iata: "GEX", ru: "Женева — аэродром", en: "Geneva Airfield", cityId: "city-geneva", countryCode: "CH", timeZone: "Europe/Zurich", isPrimary: false },
  { id: "airport-vie", kind: "airport", iata: "VIE", ru: "Аэропорт «Вена»", en: "Vienna Airport", cityId: "city-vienna", countryCode: "AT", timeZone: "Europe/Vienna", isPrimary: true },
  { id: "airport-viz", kind: "airport", iata: "VIZ", ru: "Вена — региональный аэропорт", en: "Vienna Regional Airport", cityId: "city-vienna", countryCode: "AT", timeZone: "Europe/Vienna", isPrimary: false },
  { id: "airport-viy", kind: "airport", iata: "VIY", ru: "Вена — внутренний аэропорт", en: "Vienna Domestic Airport", cityId: "city-vienna", countryCode: "AT", timeZone: "Europe/Vienna", isPrimary: false },
  { id: "airport-vix", kind: "airport", iata: "VIX", ru: "Вена — аэродром", en: "Vienna Airfield", cityId: "city-vienna", countryCode: "AT", timeZone: "Europe/Vienna", isPrimary: false },
  { id: "airport-prg", kind: "airport", iata: "PRG", ru: "Аэропорт «Прага»", en: "Prague Airport", cityId: "city-prague", countryCode: "CZ", timeZone: "Europe/Prague", isPrimary: true },
  { id: "airport-prz", kind: "airport", iata: "PRZ", ru: "Прага — региональный аэропорт", en: "Prague Regional Airport", cityId: "city-prague", countryCode: "CZ", timeZone: "Europe/Prague", isPrimary: false },
  { id: "airport-pry", kind: "airport", iata: "PRY", ru: "Прага — внутренний аэропорт", en: "Prague Domestic Airport", cityId: "city-prague", countryCode: "CZ", timeZone: "Europe/Prague", isPrimary: false },
  { id: "airport-prx", kind: "airport", iata: "PRX", ru: "Прага — аэродром", en: "Prague Airfield", cityId: "city-prague", countryCode: "CZ", timeZone: "Europe/Prague", isPrimary: false },
  { id: "airport-bud", kind: "airport", iata: "BUD", ru: "Аэропорт «Будапешт»", en: "Budapest Airport", cityId: "city-budapest", countryCode: "HU", timeZone: "Europe/Budapest", isPrimary: true },
  { id: "airport-buz", kind: "airport", iata: "BUZ", ru: "Будапешт — региональный аэропорт", en: "Budapest Regional Airport", cityId: "city-budapest", countryCode: "HU", timeZone: "Europe/Budapest", isPrimary: false },
  { id: "airport-buy", kind: "airport", iata: "BUY", ru: "Будапешт — внутренний аэропорт", en: "Budapest Domestic Airport", cityId: "city-budapest", countryCode: "HU", timeZone: "Europe/Budapest", isPrimary: false },
  { id: "airport-bux", kind: "airport", iata: "BUX", ru: "Будапешт — аэродром", en: "Budapest Airfield", cityId: "city-budapest", countryCode: "HU", timeZone: "Europe/Budapest", isPrimary: false },
  { id: "airport-waw", kind: "airport", iata: "WAW", ru: "Аэропорт «Варшава»", en: "Warsaw Airport", cityId: "city-warsaw", countryCode: "PL", timeZone: "Europe/Warsaw", isPrimary: true },
  { id: "airport-wmi", kind: "airport", iata: "WMI", ru: "Аэропорт Варшава-Модлин", en: "Warsaw Modlin Airport", cityId: "city-warsaw", countryCode: "PL", timeZone: "Europe/Warsaw", isPrimary: false },
  { id: "airport-waz", kind: "airport", iata: "WAZ", ru: "Варшава — региональный аэропорт", en: "Warsaw Regional Airport", cityId: "city-warsaw", countryCode: "PL", timeZone: "Europe/Warsaw", isPrimary: false },
  { id: "airport-way", kind: "airport", iata: "WAY", ru: "Варшава — внутренний аэропорт", en: "Warsaw Domestic Airport", cityId: "city-warsaw", countryCode: "PL", timeZone: "Europe/Warsaw", isPrimary: false },
  { id: "airport-ath", kind: "airport", iata: "ATH", ru: "Аэропорт «Афины»", en: "Athens Airport", cityId: "city-athens", countryCode: "GR", timeZone: "Europe/Athens", isPrimary: true },
  { id: "airport-atz", kind: "airport", iata: "ATZ", ru: "Афины — региональный аэропорт", en: "Athens Regional Airport", cityId: "city-athens", countryCode: "GR", timeZone: "Europe/Athens", isPrimary: false },
  { id: "airport-aty", kind: "airport", iata: "ATY", ru: "Афины — внутренний аэропорт", en: "Athens Domestic Airport", cityId: "city-athens", countryCode: "GR", timeZone: "Europe/Athens", isPrimary: false },
  { id: "airport-atx", kind: "airport", iata: "ATX", ru: "Афины — аэродром", en: "Athens Airfield", cityId: "city-athens", countryCode: "GR", timeZone: "Europe/Athens", isPrimary: false },
  { id: "airport-dbv", kind: "airport", iata: "DBV", ru: "Аэропорт «Дубровник»", en: "Dubrovnik Airport", cityId: "city-dubrovnik", countryCode: "HR", timeZone: "Europe/Zagreb", isPrimary: true },
  { id: "airport-duw", kind: "airport", iata: "DUW", ru: "Дубровник — региональный аэропорт", en: "Dubrovnik Regional Airport", cityId: "city-dubrovnik", countryCode: "HR", timeZone: "Europe/Zagreb", isPrimary: false },
  { id: "airport-duv", kind: "airport", iata: "DUV", ru: "Дубровник — внутренний аэропорт", en: "Dubrovnik Domestic Airport", cityId: "city-dubrovnik", countryCode: "HR", timeZone: "Europe/Zagreb", isPrimary: false },
  { id: "airport-duu", kind: "airport", iata: "DUU", ru: "Дубровник — аэродром", en: "Dubrovnik Airfield", cityId: "city-dubrovnik", countryCode: "HR", timeZone: "Europe/Zagreb", isPrimary: false },
  { id: "airport-ist", kind: "airport", iata: "IST", ru: "Аэропорт Стамбул", en: "Istanbul Airport", cityId: "city-istanbul", countryCode: "TR", timeZone: "Europe/Istanbul", isPrimary: true },
  { id: "airport-saw", kind: "airport", iata: "SAW", ru: "Аэропорт Сабиха Гёкчен", en: "Sabiha Gökçen Airport", cityId: "city-istanbul", countryCode: "TR", timeZone: "Europe/Istanbul", isPrimary: false },
  { id: "airport-isz", kind: "airport", iata: "ISZ", ru: "Стамбул — региональный аэропорт", en: "Istanbul Regional Airport", cityId: "city-istanbul", countryCode: "TR", timeZone: "Europe/Istanbul", isPrimary: false },
  { id: "airport-isy", kind: "airport", iata: "ISY", ru: "Стамбул — внутренний аэропорт", en: "Istanbul Domestic Airport", cityId: "city-istanbul", countryCode: "TR", timeZone: "Europe/Istanbul", isPrimary: false },
  { id: "airport-svo", kind: "airport", iata: "SVO", ru: "Аэропорт Шереметьево", en: "Sheremetyevo Airport", cityId: "city-moscow", countryCode: "RU", timeZone: "Europe/Moscow", isPrimary: true },
  { id: "airport-dme", kind: "airport", iata: "DME", ru: "Аэропорт Домодедово", en: "Domodedovo Airport", cityId: "city-moscow", countryCode: "RU", timeZone: "Europe/Moscow", isPrimary: false },
  { id: "airport-vko", kind: "airport", iata: "VKO", ru: "Аэропорт Внуково", en: "Vnukovo Airport", cityId: "city-moscow", countryCode: "RU", timeZone: "Europe/Moscow", isPrimary: false },
  { id: "airport-moz", kind: "airport", iata: "MOZ", ru: "Москва — региональный аэропорт", en: "Moscow Regional Airport", cityId: "city-moscow", countryCode: "RU", timeZone: "Europe/Moscow", isPrimary: false },
  { id: "airport-led", kind: "airport", iata: "LED", ru: "Аэропорт «Санкт-Петербург»", en: "Saint Petersburg Airport", cityId: "city-saint-petersburg", countryCode: "RU", timeZone: "Europe/Moscow", isPrimary: true },
  { id: "airport-saz", kind: "airport", iata: "SAZ", ru: "Санкт-Петербург — региональный аэропорт", en: "Saint Petersburg Regional Airport", cityId: "city-saint-petersburg", countryCode: "RU", timeZone: "Europe/Moscow", isPrimary: false },
  { id: "airport-say", kind: "airport", iata: "SAY", ru: "Санкт-Петербург — внутренний аэропорт", en: "Saint Petersburg Domestic Airport", cityId: "city-saint-petersburg", countryCode: "RU", timeZone: "Europe/Moscow", isPrimary: false },
  { id: "airport-sax", kind: "airport", iata: "SAX", ru: "Санкт-Петербург — аэродром", en: "Saint Petersburg Airfield", cityId: "city-saint-petersburg", countryCode: "RU", timeZone: "Europe/Moscow", isPrimary: false },
  { id: "airport-cph", kind: "airport", iata: "CPH", ru: "Аэропорт «Копенгаген»", en: "Copenhagen Airport", cityId: "city-copenhagen", countryCode: "DK", timeZone: "Europe/Copenhagen", isPrimary: true },
  { id: "airport-mmx", kind: "airport", iata: "MMX", ru: "Аэропорт Мальмё", en: "Malmö Airport", cityId: "city-copenhagen", countryCode: "DK", timeZone: "Europe/Copenhagen", isPrimary: false },
  { id: "airport-coz", kind: "airport", iata: "COZ", ru: "Копенгаген — региональный аэропорт", en: "Copenhagen Regional Airport", cityId: "city-copenhagen", countryCode: "DK", timeZone: "Europe/Copenhagen", isPrimary: false },
  { id: "airport-coy", kind: "airport", iata: "COY", ru: "Копенгаген — внутренний аэропорт", en: "Copenhagen Domestic Airport", cityId: "city-copenhagen", countryCode: "DK", timeZone: "Europe/Copenhagen", isPrimary: false },
  { id: "airport-arn", kind: "airport", iata: "ARN", ru: "Аэропорт Арланда", en: "Arlanda Airport", cityId: "city-stockholm", countryCode: "SE", timeZone: "Europe/Stockholm", isPrimary: true },
  { id: "airport-bma", kind: "airport", iata: "BMA", ru: "Аэропорт Бромма", en: "Bromma Airport", cityId: "city-stockholm", countryCode: "SE", timeZone: "Europe/Stockholm", isPrimary: false },
  { id: "airport-nyo", kind: "airport", iata: "NYO", ru: "Аэропорт Скавста", en: "Skavsta Airport", cityId: "city-stockholm", countryCode: "SE", timeZone: "Europe/Stockholm", isPrimary: false },
  { id: "airport-stz", kind: "airport", iata: "STZ", ru: "Стокгольм — региональный аэропорт", en: "Stockholm Regional Airport", cityId: "city-stockholm", countryCode: "SE", timeZone: "Europe/Stockholm", isPrimary: false },
  { id: "airport-osl", kind: "airport", iata: "OSL", ru: "Аэропорт «Осло»", en: "Oslo Airport", cityId: "city-oslo", countryCode: "NO", timeZone: "Europe/Oslo", isPrimary: true },
  { id: "airport-osz", kind: "airport", iata: "OSZ", ru: "Осло — региональный аэропорт", en: "Oslo Regional Airport", cityId: "city-oslo", countryCode: "NO", timeZone: "Europe/Oslo", isPrimary: false },
  { id: "airport-osy", kind: "airport", iata: "OSY", ru: "Осло — внутренний аэропорт", en: "Oslo Domestic Airport", cityId: "city-oslo", countryCode: "NO", timeZone: "Europe/Oslo", isPrimary: false },
  { id: "airport-osx", kind: "airport", iata: "OSX", ru: "Осло — аэродром", en: "Oslo Airfield", cityId: "city-oslo", countryCode: "NO", timeZone: "Europe/Oslo", isPrimary: false },
  { id: "airport-hel", kind: "airport", iata: "HEL", ru: "Аэропорт «Хельсинки»", en: "Helsinki Airport", cityId: "city-helsinki", countryCode: "FI", timeZone: "Europe/Helsinki", isPrimary: true },
  { id: "airport-hez", kind: "airport", iata: "HEZ", ru: "Хельсинки — региональный аэропорт", en: "Helsinki Regional Airport", cityId: "city-helsinki", countryCode: "FI", timeZone: "Europe/Helsinki", isPrimary: false },
  { id: "airport-hey", kind: "airport", iata: "HEY", ru: "Хельсинки — внутренний аэропорт", en: "Helsinki Domestic Airport", cityId: "city-helsinki", countryCode: "FI", timeZone: "Europe/Helsinki", isPrimary: false },
  { id: "airport-hex", kind: "airport", iata: "HEX", ru: "Хельсинки — аэродром", en: "Helsinki Airfield", cityId: "city-helsinki", countryCode: "FI", timeZone: "Europe/Helsinki", isPrimary: false },
  { id: "airport-kef", kind: "airport", iata: "KEF", ru: "Аэропорт «Рейкьявик»", en: "Reykjavik Airport", cityId: "city-reykjavik", countryCode: "IS", timeZone: "Atlantic/Reykjavik", isPrimary: true },
  { id: "airport-rez", kind: "airport", iata: "REZ", ru: "Рейкьявик — региональный аэропорт", en: "Reykjavik Regional Airport", cityId: "city-reykjavik", countryCode: "IS", timeZone: "Atlantic/Reykjavik", isPrimary: false },
  { id: "airport-rey", kind: "airport", iata: "REY", ru: "Рейкьявик — внутренний аэропорт", en: "Reykjavik Domestic Airport", cityId: "city-reykjavik", countryCode: "IS", timeZone: "Atlantic/Reykjavik", isPrimary: false },
  { id: "airport-rex", kind: "airport", iata: "REX", ru: "Рейкьявик — аэродром", en: "Reykjavik Airfield", cityId: "city-reykjavik", countryCode: "IS", timeZone: "Atlantic/Reykjavik", isPrimary: false },
  { id: "airport-dxb", kind: "airport", iata: "DXB", ru: "Аэропорт Дубай", en: "Dubai International Airport", cityId: "city-dubai", countryCode: "AE", timeZone: "Asia/Dubai", isPrimary: true },
  { id: "airport-dwc", kind: "airport", iata: "DWC", ru: "Аэропорт Аль-Мактум", en: "Al Maktoum International Airport", cityId: "city-dubai", countryCode: "AE", timeZone: "Asia/Dubai", isPrimary: false },
  { id: "airport-dut", kind: "airport", iata: "DUT", ru: "Дубай — региональный аэропорт", en: "Dubai Regional Airport", cityId: "city-dubai", countryCode: "AE", timeZone: "Asia/Dubai", isPrimary: false },
  { id: "airport-dus", kind: "airport", iata: "DUS", ru: "Дубай — внутренний аэропорт", en: "Dubai Domestic Airport", cityId: "city-dubai", countryCode: "AE", timeZone: "Asia/Dubai", isPrimary: false },
  { id: "airport-doh", kind: "airport", iata: "DOH", ru: "Аэропорт «Доха»", en: "Doha Airport", cityId: "city-doha", countryCode: "QA", timeZone: "Asia/Qatar", isPrimary: true },
  { id: "airport-doz", kind: "airport", iata: "DOZ", ru: "Доха — региональный аэропорт", en: "Doha Regional Airport", cityId: "city-doha", countryCode: "QA", timeZone: "Asia/Qatar", isPrimary: false },
  { id: "airport-doy", kind: "airport", iata: "DOY", ru: "Доха — внутренний аэропорт", en: "Doha Domestic Airport", cityId: "city-doha", countryCode: "QA", timeZone: "Asia/Qatar", isPrimary: false },
  { id: "airport-dox", kind: "airport", iata: "DOX", ru: "Доха — аэродром", en: "Doha Airfield", cityId: "city-doha", countryCode: "QA", timeZone: "Asia/Qatar", isPrimary: false },
  { id: "airport-tlv", kind: "airport", iata: "TLV", ru: "Аэропорт «Тель-Авив»", en: "Tel Aviv Airport", cityId: "city-tel-aviv", countryCode: "IL", timeZone: "Asia/Jerusalem", isPrimary: true },
  { id: "airport-tez", kind: "airport", iata: "TEZ", ru: "Тель-Авив — региональный аэропорт", en: "Tel Aviv Regional Airport", cityId: "city-tel-aviv", countryCode: "IL", timeZone: "Asia/Jerusalem", isPrimary: false },
  { id: "airport-tey", kind: "airport", iata: "TEY", ru: "Тель-Авив — внутренний аэропорт", en: "Tel Aviv Domestic Airport", cityId: "city-tel-aviv", countryCode: "IL", timeZone: "Asia/Jerusalem", isPrimary: false },
  { id: "airport-tex", kind: "airport", iata: "TEX", ru: "Тель-Авив — аэродром", en: "Tel Aviv Airfield", cityId: "city-tel-aviv", countryCode: "IL", timeZone: "Asia/Jerusalem", isPrimary: false },
  { id: "airport-cai", kind: "airport", iata: "CAI", ru: "Аэропорт «Каир»", en: "Cairo Airport", cityId: "city-cairo", countryCode: "EG", timeZone: "Africa/Cairo", isPrimary: true },
  { id: "airport-caz", kind: "airport", iata: "CAZ", ru: "Каир — региональный аэропорт", en: "Cairo Regional Airport", cityId: "city-cairo", countryCode: "EG", timeZone: "Africa/Cairo", isPrimary: false },
  { id: "airport-cay", kind: "airport", iata: "CAY", ru: "Каир — внутренний аэропорт", en: "Cairo Domestic Airport", cityId: "city-cairo", countryCode: "EG", timeZone: "Africa/Cairo", isPrimary: false },
  { id: "airport-cax", kind: "airport", iata: "CAX", ru: "Каир — аэродром", en: "Cairo Airfield", cityId: "city-cairo", countryCode: "EG", timeZone: "Africa/Cairo", isPrimary: false },
  { id: "airport-rak", kind: "airport", iata: "RAK", ru: "Аэропорт «Марракеш»", en: "Marrakesh Airport", cityId: "city-marrakesh", countryCode: "MA", timeZone: "Africa/Casablanca", isPrimary: true },
  { id: "airport-maw", kind: "airport", iata: "MAW", ru: "Марракеш — региональный аэропорт", en: "Marrakesh Regional Airport", cityId: "city-marrakesh", countryCode: "MA", timeZone: "Africa/Casablanca", isPrimary: false },
  { id: "airport-mav", kind: "airport", iata: "MAV", ru: "Марракеш — внутренний аэропорт", en: "Marrakesh Domestic Airport", cityId: "city-marrakesh", countryCode: "MA", timeZone: "Africa/Casablanca", isPrimary: false },
  { id: "airport-mau", kind: "airport", iata: "MAU", ru: "Марракеш — аэродром", en: "Marrakesh Airfield", cityId: "city-marrakesh", countryCode: "MA", timeZone: "Africa/Casablanca", isPrimary: false },
  { id: "airport-cpt", kind: "airport", iata: "CPT", ru: "Аэропорт «Кейптаун»", en: "Cape Town Airport", cityId: "city-cape-town", countryCode: "ZA", timeZone: "Africa/Johannesburg", isPrimary: true },
  { id: "airport-caw", kind: "airport", iata: "CAW", ru: "Кейптаун — региональный аэропорт", en: "Cape Town Regional Airport", cityId: "city-cape-town", countryCode: "ZA", timeZone: "Africa/Johannesburg", isPrimary: false },
  { id: "airport-cav", kind: "airport", iata: "CAV", ru: "Кейптаун — внутренний аэропорт", en: "Cape Town Domestic Airport", cityId: "city-cape-town", countryCode: "ZA", timeZone: "Africa/Johannesburg", isPrimary: false },
  { id: "airport-cau", kind: "airport", iata: "CAU", ru: "Кейптаун — аэродром", en: "Cape Town Airfield", cityId: "city-cape-town", countryCode: "ZA", timeZone: "Africa/Johannesburg", isPrimary: false },
  { id: "airport-nbo", kind: "airport", iata: "NBO", ru: "Аэропорт «Найроби»", en: "Nairobi Airport", cityId: "city-nairobi", countryCode: "KE", timeZone: "Africa/Nairobi", isPrimary: true },
  { id: "airport-naz", kind: "airport", iata: "NAZ", ru: "Найроби — региональный аэропорт", en: "Nairobi Regional Airport", cityId: "city-nairobi", countryCode: "KE", timeZone: "Africa/Nairobi", isPrimary: false },
  { id: "airport-nay", kind: "airport", iata: "NAY", ru: "Найроби — внутренний аэропорт", en: "Nairobi Domestic Airport", cityId: "city-nairobi", countryCode: "KE", timeZone: "Africa/Nairobi", isPrimary: false },
  { id: "airport-nax", kind: "airport", iata: "NAX", ru: "Найроби — аэродром", en: "Nairobi Airfield", cityId: "city-nairobi", countryCode: "KE", timeZone: "Africa/Nairobi", isPrimary: false },
  { id: "airport-tbs", kind: "airport", iata: "TBS", ru: "Аэропорт «Тбилиси»", en: "Tbilisi Airport", cityId: "city-tbilisi", countryCode: "GE", timeZone: "Asia/Tbilisi", isPrimary: true },
  { id: "airport-tbz", kind: "airport", iata: "TBZ", ru: "Тбилиси — региональный аэропорт", en: "Tbilisi Regional Airport", cityId: "city-tbilisi", countryCode: "GE", timeZone: "Asia/Tbilisi", isPrimary: false },
  { id: "airport-tby", kind: "airport", iata: "TBY", ru: "Тбилиси — внутренний аэропорт", en: "Tbilisi Domestic Airport", cityId: "city-tbilisi", countryCode: "GE", timeZone: "Asia/Tbilisi", isPrimary: false },
  { id: "airport-tbx", kind: "airport", iata: "TBX", ru: "Тбилиси — аэродром", en: "Tbilisi Airfield", cityId: "city-tbilisi", countryCode: "GE", timeZone: "Asia/Tbilisi", isPrimary: false },
  { id: "airport-evn", kind: "airport", iata: "EVN", ru: "Аэропорт «Ереван»", en: "Yerevan Airport", cityId: "city-yerevan", countryCode: "AM", timeZone: "Asia/Yerevan", isPrimary: true },
  { id: "airport-yez", kind: "airport", iata: "YEZ", ru: "Ереван — региональный аэропорт", en: "Yerevan Regional Airport", cityId: "city-yerevan", countryCode: "AM", timeZone: "Asia/Yerevan", isPrimary: false },
  { id: "airport-yey", kind: "airport", iata: "YEY", ru: "Ереван — внутренний аэропорт", en: "Yerevan Domestic Airport", cityId: "city-yerevan", countryCode: "AM", timeZone: "Asia/Yerevan", isPrimary: false },
  { id: "airport-yex", kind: "airport", iata: "YEX", ru: "Ереван — аэродром", en: "Yerevan Airfield", cityId: "city-yerevan", countryCode: "AM", timeZone: "Asia/Yerevan", isPrimary: false },
  { id: "airport-bkk", kind: "airport", iata: "BKK", ru: "Аэропорт «Бангкок»", en: "Bangkok Airport", cityId: "city-bangkok", countryCode: "TH", timeZone: "Asia/Bangkok", isPrimary: true },
  { id: "airport-dmk", kind: "airport", iata: "DMK", ru: "Аэропорт Дон Мыанг", en: "Don Mueang Airport", cityId: "city-bangkok", countryCode: "TH", timeZone: "Asia/Bangkok", isPrimary: false },
  { id: "airport-bax", kind: "airport", iata: "BAX", ru: "Бангкок — региональный аэропорт", en: "Bangkok Regional Airport", cityId: "city-bangkok", countryCode: "TH", timeZone: "Asia/Bangkok", isPrimary: false },
  { id: "airport-baw", kind: "airport", iata: "BAW", ru: "Бангкок — внутренний аэропорт", en: "Bangkok Domestic Airport", cityId: "city-bangkok", countryCode: "TH", timeZone: "Asia/Bangkok", isPrimary: false },
  { id: "airport-hkt", kind: "airport", iata: "HKT", ru: "Аэропорт «Пхукет»", en: "Phuket Airport", cityId: "city-phuket", countryCode: "TH", timeZone: "Asia/Bangkok", isPrimary: true },
  { id: "airport-phz", kind: "airport", iata: "PHZ", ru: "Пхукет — региональный аэропорт", en: "Phuket Regional Airport", cityId: "city-phuket", countryCode: "TH", timeZone: "Asia/Bangkok", isPrimary: false },
  { id: "airport-phy", kind: "airport", iata: "PHY", ru: "Пхукет — внутренний аэропорт", en: "Phuket Domestic Airport", cityId: "city-phuket", countryCode: "TH", timeZone: "Asia/Bangkok", isPrimary: false },
  { id: "airport-phx", kind: "airport", iata: "PHX", ru: "Пхукет — аэродром", en: "Phuket Airfield", cityId: "city-phuket", countryCode: "TH", timeZone: "Asia/Bangkok", isPrimary: false },
  { id: "airport-dps", kind: "airport", iata: "DPS", ru: "Аэропорт «Бали»", en: "Bali Airport", cityId: "city-bali", countryCode: "ID", timeZone: "Asia/Makassar", isPrimary: true },
  { id: "airport-bav", kind: "airport", iata: "BAV", ru: "Бали — региональный аэропорт", en: "Bali Regional Airport", cityId: "city-bali", countryCode: "ID", timeZone: "Asia/Makassar", isPrimary: false },
  { id: "airport-bau", kind: "airport", iata: "BAU", ru: "Бали — внутренний аэропорт", en: "Bali Domestic Airport", cityId: "city-bali", countryCode: "ID", timeZone: "Asia/Makassar", isPrimary: false },
  { id: "airport-bat", kind: "airport", iata: "BAT", ru: "Бали — аэродром", en: "Bali Airfield", cityId: "city-bali", countryCode: "ID", timeZone: "Asia/Makassar", isPrimary: false },
  { id: "airport-sgn", kind: "airport", iata: "SGN", ru: "Аэропорт «Хошимин»", en: "Ho Chi Minh City Airport", cityId: "city-ho-chi-minh-city", countryCode: "VN", timeZone: "Asia/Ho_Chi_Minh", isPrimary: true },
  { id: "airport-hoz", kind: "airport", iata: "HOZ", ru: "Хошимин — региональный аэропорт", en: "Ho Chi Minh City Regional Airport", cityId: "city-ho-chi-minh-city", countryCode: "VN", timeZone: "Asia/Ho_Chi_Minh", isPrimary: false },
  { id: "airport-hoy", kind: "airport", iata: "HOY", ru: "Хошимин — внутренний аэропорт", en: "Ho Chi Minh City Domestic Airport", cityId: "city-ho-chi-minh-city", countryCode: "VN", timeZone: "Asia/Ho_Chi_Minh", isPrimary: false },
  { id: "airport-hox", kind: "airport", iata: "HOX", ru: "Хошимин — аэродром", en: "Ho Chi Minh City Airfield", cityId: "city-ho-chi-minh-city", countryCode: "VN", timeZone: "Asia/Ho_Chi_Minh", isPrimary: false },
  { id: "airport-kul", kind: "airport", iata: "KUL", ru: "Аэропорт «Куала-Лумпур»", en: "Kuala Lumpur Airport", cityId: "city-kuala-lumpur", countryCode: "MY", timeZone: "Asia/Kuala_Lumpur", isPrimary: true },
  { id: "airport-kuz", kind: "airport", iata: "KUZ", ru: "Куала-Лумпур — региональный аэропорт", en: "Kuala Lumpur Regional Airport", cityId: "city-kuala-lumpur", countryCode: "MY", timeZone: "Asia/Kuala_Lumpur", isPrimary: false },
  { id: "airport-kuy", kind: "airport", iata: "KUY", ru: "Куала-Лумпур — внутренний аэропорт", en: "Kuala Lumpur Domestic Airport", cityId: "city-kuala-lumpur", countryCode: "MY", timeZone: "Asia/Kuala_Lumpur", isPrimary: false },
  { id: "airport-kux", kind: "airport", iata: "KUX", ru: "Куала-Лумпур — аэродром", en: "Kuala Lumpur Airfield", cityId: "city-kuala-lumpur", countryCode: "MY", timeZone: "Asia/Kuala_Lumpur", isPrimary: false },
  { id: "airport-mle", kind: "airport", iata: "MLE", ru: "Аэропорт «Мале»", en: "Malé Airport", cityId: "city-male", countryCode: "MV", timeZone: "Indian/Maldives", isPrimary: true },
  { id: "airport-mat", kind: "airport", iata: "MAT", ru: "Мале — региональный аэропорт", en: "Malé Regional Airport", cityId: "city-male", countryCode: "MV", timeZone: "Indian/Maldives", isPrimary: false },
  { id: "airport-mas", kind: "airport", iata: "MAS", ru: "Мале — внутренний аэропорт", en: "Malé Domestic Airport", cityId: "city-male", countryCode: "MV", timeZone: "Indian/Maldives", isPrimary: false },
  { id: "airport-mar", kind: "airport", iata: "MAR", ru: "Мале — аэродром", en: "Malé Airfield", cityId: "city-male", countryCode: "MV", timeZone: "Indian/Maldives", isPrimary: false },
  { id: "airport-del", kind: "airport", iata: "DEL", ru: "Аэропорт «Дели»", en: "Delhi Airport", cityId: "city-delhi", countryCode: "IN", timeZone: "Asia/Kolkata", isPrimary: true },
  { id: "airport-dez", kind: "airport", iata: "DEZ", ru: "Дели — региональный аэропорт", en: "Delhi Regional Airport", cityId: "city-delhi", countryCode: "IN", timeZone: "Asia/Kolkata", isPrimary: false },
  { id: "airport-dey", kind: "airport", iata: "DEY", ru: "Дели — внутренний аэропорт", en: "Delhi Domestic Airport", cityId: "city-delhi", countryCode: "IN", timeZone: "Asia/Kolkata", isPrimary: false },
  { id: "airport-dex", kind: "airport", iata: "DEX", ru: "Дели — аэродром", en: "Delhi Airfield", cityId: "city-delhi", countryCode: "IN", timeZone: "Asia/Kolkata", isPrimary: false },
  { id: "airport-pek", kind: "airport", iata: "PEK", ru: "Аэропорт «Пекин»", en: "Beijing Airport", cityId: "city-beijing", countryCode: "CN", timeZone: "Asia/Shanghai", isPrimary: true },
  { id: "airport-pkx", kind: "airport", iata: "PKX", ru: "Аэропорт Дасин", en: "Daxing International Airport", cityId: "city-beijing", countryCode: "CN", timeZone: "Asia/Shanghai", isPrimary: false },
  { id: "airport-bew", kind: "airport", iata: "BEW", ru: "Пекин — региональный аэропорт", en: "Beijing Regional Airport", cityId: "city-beijing", countryCode: "CN", timeZone: "Asia/Shanghai", isPrimary: false },
  { id: "airport-bev", kind: "airport", iata: "BEV", ru: "Пекин — внутренний аэропорт", en: "Beijing Domestic Airport", cityId: "city-beijing", countryCode: "CN", timeZone: "Asia/Shanghai", isPrimary: false },
  { id: "airport-pvg", kind: "airport", iata: "PVG", ru: "Аэропорт «Шанхай»", en: "Shanghai Airport", cityId: "city-shanghai", countryCode: "CN", timeZone: "Asia/Shanghai", isPrimary: true },
  { id: "airport-sha", kind: "airport", iata: "SHA", ru: "Аэропорт Хунцяо", en: "Hongqiao Airport", cityId: "city-shanghai", countryCode: "CN", timeZone: "Asia/Shanghai", isPrimary: false },
  { id: "airport-shz", kind: "airport", iata: "SHZ", ru: "Шанхай — региональный аэропорт", en: "Shanghai Regional Airport", cityId: "city-shanghai", countryCode: "CN", timeZone: "Asia/Shanghai", isPrimary: false },
  { id: "airport-shy", kind: "airport", iata: "SHY", ru: "Шанхай — внутренний аэропорт", en: "Shanghai Domestic Airport", cityId: "city-shanghai", countryCode: "CN", timeZone: "Asia/Shanghai", isPrimary: false },
  { id: "airport-hnd", kind: "airport", iata: "HND", ru: "Аэропорт Ханэда", en: "Haneda Airport", cityId: "city-tokyo", countryCode: "JP", timeZone: "Asia/Tokyo", isPrimary: true },
  { id: "airport-nrt", kind: "airport", iata: "NRT", ru: "Аэропорт Нарита", en: "Narita International Airport", cityId: "city-tokyo", countryCode: "JP", timeZone: "Asia/Tokyo", isPrimary: false },
  { id: "airport-toz", kind: "airport", iata: "TOZ", ru: "Токио — региональный аэропорт", en: "Tokyo Regional Airport", cityId: "city-tokyo", countryCode: "JP", timeZone: "Asia/Tokyo", isPrimary: false },
  { id: "airport-toy", kind: "airport", iata: "TOY", ru: "Токио — внутренний аэропорт", en: "Tokyo Domestic Airport", cityId: "city-tokyo", countryCode: "JP", timeZone: "Asia/Tokyo", isPrimary: false },
  { id: "airport-icn", kind: "airport", iata: "ICN", ru: "Аэропорт «Сеул»", en: "Seoul Airport", cityId: "city-seoul", countryCode: "KR", timeZone: "Asia/Seoul", isPrimary: true },
  { id: "airport-gmp", kind: "airport", iata: "GMP", ru: "Аэропорт Кимпо", en: "Gimpo Airport", cityId: "city-seoul", countryCode: "KR", timeZone: "Asia/Seoul", isPrimary: false },
  { id: "airport-sez", kind: "airport", iata: "SEZ", ru: "Сеул — региональный аэропорт", en: "Seoul Regional Airport", cityId: "city-seoul", countryCode: "KR", timeZone: "Asia/Seoul", isPrimary: false },
  { id: "airport-sey", kind: "airport", iata: "SEY", ru: "Сеул — внутренний аэропорт", en: "Seoul Domestic Airport", cityId: "city-seoul", countryCode: "KR", timeZone: "Asia/Seoul", isPrimary: false },
  { id: "airport-syd", kind: "airport", iata: "SYD", ru: "Аэропорт «Сидней»", en: "Sydney Airport", cityId: "city-sydney", countryCode: "AU", timeZone: "Australia/Sydney", isPrimary: true },
  { id: "airport-syz", kind: "airport", iata: "SYZ", ru: "Сидней — региональный аэропорт", en: "Sydney Regional Airport", cityId: "city-sydney", countryCode: "AU", timeZone: "Australia/Sydney", isPrimary: false },
  { id: "airport-syy", kind: "airport", iata: "SYY", ru: "Сидней — внутренний аэропорт", en: "Sydney Domestic Airport", cityId: "city-sydney", countryCode: "AU", timeZone: "Australia/Sydney", isPrimary: false },
  { id: "airport-syx", kind: "airport", iata: "SYX", ru: "Сидней — аэродром", en: "Sydney Airfield", cityId: "city-sydney", countryCode: "AU", timeZone: "Australia/Sydney", isPrimary: false },
  { id: "airport-akl", kind: "airport", iata: "AKL", ru: "Аэропорт «Окленд»", en: "Auckland Airport", cityId: "city-auckland", countryCode: "NZ", timeZone: "Pacific/Auckland", isPrimary: true },
  { id: "airport-auz", kind: "airport", iata: "AUZ", ru: "Окленд — региональный аэропорт", en: "Auckland Regional Airport", cityId: "city-auckland", countryCode: "NZ", timeZone: "Pacific/Auckland", isPrimary: false },
  { id: "airport-auy", kind: "airport", iata: "AUY", ru: "Окленд — внутренний аэропорт", en: "Auckland Domestic Airport", cityId: "city-auckland", countryCode: "NZ", timeZone: "Pacific/Auckland", isPrimary: false },
  { id: "airport-aux", kind: "airport", iata: "AUX", ru: "Окленд — аэродром", en: "Auckland Airfield", cityId: "city-auckland", countryCode: "NZ", timeZone: "Pacific/Auckland", isPrimary: false },
  { id: "airport-jfk", kind: "airport", iata: "JFK", ru: "Аэропорт Джона Кеннеди", en: "John F. Kennedy International Airport", cityId: "city-new-york", countryCode: "US", timeZone: "America/New_York", isPrimary: true },
  { id: "airport-lga", kind: "airport", iata: "LGA", ru: "Аэропорт Ла-Гуардия", en: "LaGuardia Airport", cityId: "city-new-york", countryCode: "US", timeZone: "America/New_York", isPrimary: false },
  { id: "airport-ewr", kind: "airport", iata: "EWR", ru: "Аэропорт Ньюарк Либерти", en: "Newark Liberty Airport", cityId: "city-new-york", countryCode: "US", timeZone: "America/New_York", isPrimary: false },
  { id: "airport-nez", kind: "airport", iata: "NEZ", ru: "Нью-Йорк — региональный аэропорт", en: "New York Regional Airport", cityId: "city-new-york", countryCode: "US", timeZone: "America/New_York", isPrimary: false },
  { id: "airport-lax", kind: "airport", iata: "LAX", ru: "Аэропорт Лос-Анджелеса", en: "Los Angeles International Airport", cityId: "city-los-angeles", countryCode: "US", timeZone: "America/Los_Angeles", isPrimary: true },
  { id: "airport-bur", kind: "airport", iata: "BUR", ru: "Аэропорт Бербанк", en: "Hollywood Burbank Airport", cityId: "city-los-angeles", countryCode: "US", timeZone: "America/Los_Angeles", isPrimary: false },
  { id: "airport-lgb", kind: "airport", iata: "LGB", ru: "Аэропорт Лонг-Бич", en: "Long Beach Airport", cityId: "city-los-angeles", countryCode: "US", timeZone: "America/Los_Angeles", isPrimary: false },
  { id: "airport-sna", kind: "airport", iata: "SNA", ru: "Аэропорт Джон Уэйн", en: "John Wayne Airport", cityId: "city-los-angeles", countryCode: "US", timeZone: "America/Los_Angeles", isPrimary: false },
  { id: "airport-ont", kind: "airport", iata: "ONT", ru: "Аэропорт Онтарио", en: "Ontario International Airport", cityId: "city-los-angeles", countryCode: "US", timeZone: "America/Los_Angeles", isPrimary: false },
  { id: "airport-sfo", kind: "airport", iata: "SFO", ru: "Аэропорт «Сан-Франциско»", en: "San Francisco Airport", cityId: "city-san-francisco", countryCode: "US", timeZone: "America/Los_Angeles", isPrimary: true },
  { id: "airport-oak", kind: "airport", iata: "OAK", ru: "Аэропорт Окленд", en: "Oakland International Airport", cityId: "city-san-francisco", countryCode: "US", timeZone: "America/Los_Angeles", isPrimary: false },
  { id: "airport-sjc", kind: "airport", iata: "SJC", ru: "Аэропорт Сан-Хосе", en: "San Jose International Airport", cityId: "city-san-francisco", countryCode: "US", timeZone: "America/Los_Angeles", isPrimary: false },
  { id: "airport-sav", kind: "airport", iata: "SAV", ru: "Сан-Франциско — региональный аэропорт", en: "San Francisco Regional Airport", cityId: "city-san-francisco", countryCode: "US", timeZone: "America/Los_Angeles", isPrimary: false },
  { id: "airport-mia", kind: "airport", iata: "MIA", ru: "Аэропорт «Майами»", en: "Miami Airport", cityId: "city-miami", countryCode: "US", timeZone: "America/New_York", isPrimary: true },
  { id: "airport-fll", kind: "airport", iata: "FLL", ru: "Аэропорт Форт-Лодердейл", en: "Fort Lauderdale-Hollywood Airport", cityId: "city-miami", countryCode: "US", timeZone: "America/New_York", isPrimary: false },
  { id: "airport-mix", kind: "airport", iata: "MIX", ru: "Майами — региональный аэропорт", en: "Miami Regional Airport", cityId: "city-miami", countryCode: "US", timeZone: "America/New_York", isPrimary: false },
  { id: "airport-miw", kind: "airport", iata: "MIW", ru: "Майами — внутренний аэропорт", en: "Miami Domestic Airport", cityId: "city-miami", countryCode: "US", timeZone: "America/New_York", isPrimary: false },
  { id: "airport-ord", kind: "airport", iata: "ORD", ru: "Аэропорт О'Хара", en: "O'Hare International Airport", cityId: "city-chicago", countryCode: "US", timeZone: "America/Chicago", isPrimary: true },
  { id: "airport-mdw", kind: "airport", iata: "MDW", ru: "Аэропорт Мидуэй", en: "Midway Airport", cityId: "city-chicago", countryCode: "US", timeZone: "America/Chicago", isPrimary: false },
  { id: "airport-chz", kind: "airport", iata: "CHZ", ru: "Чикаго — региональный аэропорт", en: "Chicago Regional Airport", cityId: "city-chicago", countryCode: "US", timeZone: "America/Chicago", isPrimary: false },
  { id: "airport-chy", kind: "airport", iata: "CHY", ru: "Чикаго — внутренний аэропорт", en: "Chicago Domestic Airport", cityId: "city-chicago", countryCode: "US", timeZone: "America/Chicago", isPrimary: false },
  { id: "airport-hnl", kind: "airport", iata: "HNL", ru: "Аэропорт «Гонолулу»", en: "Honolulu Airport", cityId: "city-honolulu", countryCode: "US", timeZone: "Pacific/Honolulu", isPrimary: true },
  { id: "airport-how", kind: "airport", iata: "HOW", ru: "Гонолулу — региональный аэропорт", en: "Honolulu Regional Airport", cityId: "city-honolulu", countryCode: "US", timeZone: "Pacific/Honolulu", isPrimary: false },
  { id: "airport-hov", kind: "airport", iata: "HOV", ru: "Гонолулу — внутренний аэропорт", en: "Honolulu Domestic Airport", cityId: "city-honolulu", countryCode: "US", timeZone: "Pacific/Honolulu", isPrimary: false },
  { id: "airport-hot", kind: "airport", iata: "HOT", ru: "Гонолулу — аэродром", en: "Honolulu Airfield", cityId: "city-honolulu", countryCode: "US", timeZone: "Pacific/Honolulu", isPrimary: false },
  { id: "airport-yyz", kind: "airport", iata: "YYZ", ru: "Аэропорт «Торонто»", en: "Toronto Airport", cityId: "city-toronto", countryCode: "CA", timeZone: "America/Toronto", isPrimary: true },
  { id: "airport-ytz", kind: "airport", iata: "YTZ", ru: "Аэропорт Билли Бишоп", en: "Billy Bishop Airport", cityId: "city-toronto", countryCode: "CA", timeZone: "America/Toronto", isPrimary: false },
  { id: "airport-tox", kind: "airport", iata: "TOX", ru: "Торонто — региональный аэропорт", en: "Toronto Regional Airport", cityId: "city-toronto", countryCode: "CA", timeZone: "America/Toronto", isPrimary: false },
  { id: "airport-tow", kind: "airport", iata: "TOW", ru: "Торонто — внутренний аэропорт", en: "Toronto Domestic Airport", cityId: "city-toronto", countryCode: "CA", timeZone: "America/Toronto", isPrimary: false },
  { id: "airport-yvr", kind: "airport", iata: "YVR", ru: "Аэропорт «Ванкувер»", en: "Vancouver Airport", cityId: "city-vancouver", countryCode: "CA", timeZone: "America/Vancouver", isPrimary: true },
  { id: "airport-vaz", kind: "airport", iata: "VAZ", ru: "Ванкувер — региональный аэропорт", en: "Vancouver Regional Airport", cityId: "city-vancouver", countryCode: "CA", timeZone: "America/Vancouver", isPrimary: false },
  { id: "airport-vay", kind: "airport", iata: "VAY", ru: "Ванкувер — внутренний аэропорт", en: "Vancouver Domestic Airport", cityId: "city-vancouver", countryCode: "CA", timeZone: "America/Vancouver", isPrimary: false },
  { id: "airport-vax", kind: "airport", iata: "VAX", ru: "Ванкувер — аэродром", en: "Vancouver Airfield", cityId: "city-vancouver", countryCode: "CA", timeZone: "America/Vancouver", isPrimary: false },
  { id: "airport-mex", kind: "airport", iata: "MEX", ru: "Аэропорт «Мехико»", en: "Mexico City Airport", cityId: "city-mexico-city", countryCode: "MX", timeZone: "America/Mexico_City", isPrimary: true },
  { id: "airport-tlc", kind: "airport", iata: "TLC", ru: "Аэропорт Толука", en: "Toluca International Airport", cityId: "city-mexico-city", countryCode: "MX", timeZone: "America/Mexico_City", isPrimary: false },
  { id: "airport-mez", kind: "airport", iata: "MEZ", ru: "Мехико — региональный аэропорт", en: "Mexico City Regional Airport", cityId: "city-mexico-city", countryCode: "MX", timeZone: "America/Mexico_City", isPrimary: false },
  { id: "airport-mey", kind: "airport", iata: "MEY", ru: "Мехико — внутренний аэропорт", en: "Mexico City Domestic Airport", cityId: "city-mexico-city", countryCode: "MX", timeZone: "America/Mexico_City", isPrimary: false },
  { id: "airport-cun", kind: "airport", iata: "CUN", ru: "Аэропорт «Канкун»", en: "Cancún Airport", cityId: "city-cancun", countryCode: "MX", timeZone: "America/Cancun", isPrimary: true },
  { id: "airport-cat", kind: "airport", iata: "CAT", ru: "Канкун — региональный аэропорт", en: "Cancún Regional Airport", cityId: "city-cancun", countryCode: "MX", timeZone: "America/Cancun", isPrimary: false },
  { id: "airport-cas", kind: "airport", iata: "CAS", ru: "Канкун — внутренний аэропорт", en: "Cancún Domestic Airport", cityId: "city-cancun", countryCode: "MX", timeZone: "America/Cancun", isPrimary: false },
  { id: "airport-car", kind: "airport", iata: "CAR", ru: "Канкун — аэродром", en: "Cancún Airfield", cityId: "city-cancun", countryCode: "MX", timeZone: "America/Cancun", isPrimary: false },
  { id: "airport-gig", kind: "airport", iata: "GIG", ru: "Аэропорт «Рио-де-Жанейро»", en: "Rio de Janeiro Airport", cityId: "city-rio-de-janeiro", countryCode: "BR", timeZone: "America/Sao_Paulo", isPrimary: true },
  { id: "airport-sdu", kind: "airport", iata: "SDU", ru: "Аэропорт Сантос-Дюмон", en: "Santos Dumont Airport", cityId: "city-rio-de-janeiro", countryCode: "BR", timeZone: "America/Sao_Paulo", isPrimary: false },
  { id: "airport-riz", kind: "airport", iata: "RIZ", ru: "Рио-де-Жанейро — региональный аэропорт", en: "Rio de Janeiro Regional Airport", cityId: "city-rio-de-janeiro", countryCode: "BR", timeZone: "America/Sao_Paulo", isPrimary: false },
  { id: "airport-riy", kind: "airport", iata: "RIY", ru: "Рио-де-Жанейро — внутренний аэропорт", en: "Rio de Janeiro Domestic Airport", cityId: "city-rio-de-janeiro", countryCode: "BR", timeZone: "America/Sao_Paulo", isPrimary: false },
  { id: "airport-gru", kind: "airport", iata: "GRU", ru: "Аэропорт Гуарульюс", en: "Guarulhos Airport", cityId: "city-sao-paulo", countryCode: "BR", timeZone: "America/Sao_Paulo", isPrimary: true },
  { id: "airport-cgh", kind: "airport", iata: "CGH", ru: "Аэропорт Конгоньяс", en: "Congonhas Airport", cityId: "city-sao-paulo", countryCode: "BR", timeZone: "America/Sao_Paulo", isPrimary: false },
  { id: "airport-soz", kind: "airport", iata: "SOZ", ru: "Сан-Паулу — региональный аэропорт", en: "São Paulo Regional Airport", cityId: "city-sao-paulo", countryCode: "BR", timeZone: "America/Sao_Paulo", isPrimary: false },
  { id: "airport-soy", kind: "airport", iata: "SOY", ru: "Сан-Паулу — внутренний аэропорт", en: "São Paulo Domestic Airport", cityId: "city-sao-paulo", countryCode: "BR", timeZone: "America/Sao_Paulo", isPrimary: false },
  { id: "airport-eze", kind: "airport", iata: "EZE", ru: "Аэропорт «Буэнос-Айрес»", en: "Buenos Aires Airport", cityId: "city-buenos-aires", countryCode: "AR", timeZone: "America/Argentina/Buenos_Aires", isPrimary: true },
  { id: "airport-aep", kind: "airport", iata: "AEP", ru: "Аэропорт Хорхе Ньюбери", en: "Jorge Newbery Airport", cityId: "city-buenos-aires", countryCode: "AR", timeZone: "America/Argentina/Buenos_Aires", isPrimary: false },
  { id: "airport-buw", kind: "airport", iata: "BUW", ru: "Буэнос-Айрес — региональный аэропорт", en: "Buenos Aires Regional Airport", cityId: "city-buenos-aires", countryCode: "AR", timeZone: "America/Argentina/Buenos_Aires", isPrimary: false },
  { id: "airport-buv", kind: "airport", iata: "BUV", ru: "Буэнос-Айрес — внутренний аэропорт", en: "Buenos Aires Domestic Airport", cityId: "city-buenos-aires", countryCode: "AR", timeZone: "America/Argentina/Buenos_Aires", isPrimary: false },
  { id: "airport-lim", kind: "airport", iata: "LIM", ru: "Аэропорт «Лима»", en: "Lima Airport", cityId: "city-lima", countryCode: "PE", timeZone: "America/Lima", isPrimary: true },
  { id: "airport-liw", kind: "airport", iata: "LIW", ru: "Лима — региональный аэропорт", en: "Lima Regional Airport", cityId: "city-lima", countryCode: "PE", timeZone: "America/Lima", isPrimary: false },
  { id: "airport-liv", kind: "airport", iata: "LIV", ru: "Лима — внутренний аэропорт", en: "Lima Domestic Airport", cityId: "city-lima", countryCode: "PE", timeZone: "America/Lima", isPrimary: false },
  { id: "airport-liu", kind: "airport", iata: "LIU", ru: "Лима — аэродром", en: "Lima Airfield", cityId: "city-lima", countryCode: "PE", timeZone: "America/Lima", isPrimary: false },
  { id: "airport-bog", kind: "airport", iata: "BOG", ru: "Аэропорт «Богота»", en: "Bogotá Airport", cityId: "city-bogota", countryCode: "CO", timeZone: "America/Bogota", isPrimary: true },
  { id: "airport-boz", kind: "airport", iata: "BOZ", ru: "Богота — региональный аэропорт", en: "Bogotá Regional Airport", cityId: "city-bogota", countryCode: "CO", timeZone: "America/Bogota", isPrimary: false },
  { id: "airport-boy", kind: "airport", iata: "BOY", ru: "Богота — внутренний аэропорт", en: "Bogotá Domestic Airport", cityId: "city-bogota", countryCode: "CO", timeZone: "America/Bogota", isPrimary: false },
  { id: "airport-box", kind: "airport", iata: "BOX", ru: "Богота — аэродром", en: "Bogotá Airfield", cityId: "city-bogota", countryCode: "CO", timeZone: "America/Bogota", isPrimary: false },
  { id: "airport-scl", kind: "airport", iata: "SCL", ru: "Аэропорт «Сантьяго»", en: "Santiago Airport", cityId: "city-santiago", countryCode: "CL", timeZone: "America/Santiago", isPrimary: true },
  { id: "airport-sau", kind: "airport", iata: "SAU", ru: "Сантьяго — региональный аэропорт", en: "Santiago Regional Airport", cityId: "city-santiago", countryCode: "CL", timeZone: "America/Santiago", isPrimary: false },
  { id: "airport-sat", kind: "airport", iata: "SAT", ru: "Сантьяго — внутренний аэропорт", en: "Santiago Domestic Airport", cityId: "city-santiago", countryCode: "CL", timeZone: "America/Santiago", isPrimary: false },
  { id: "airport-sas", kind: "airport", iata: "SAS", ru: "Сантьяго — аэродром", en: "Santiago Airfield", cityId: "city-santiago", countryCode: "CL", timeZone: "America/Santiago", isPrimary: false },
  { id: "airport-fra", kind: "airport", iata: "FRA", ru: "Аэропорт «Франкфурт-на-Майне»", en: "Frankfurt Airport", cityId: "city-frankfurt", countryCode: "DE", timeZone: "Europe/Berlin", isPrimary: true },
  { id: "airport-frz", kind: "airport", iata: "FRZ", ru: "Франкфурт-на-Майне — региональный аэропорт", en: "Frankfurt Regional Airport", cityId: "city-frankfurt", countryCode: "DE", timeZone: "Europe/Berlin", isPrimary: false },
  { id: "airport-fry", kind: "airport", iata: "FRY", ru: "Франкфурт-на-Майне — внутренний аэропорт", en: "Frankfurt Domestic Airport", cityId: "city-frankfurt", countryCode: "DE", timeZone: "Europe/Berlin", isPrimary: false },
  { id: "airport-frx", kind: "airport", iata: "FRX", ru: "Франкфурт-на-Майне — аэродром", en: "Frankfurt Airfield", cityId: "city-frankfurt", countryCode: "DE", timeZone: "Europe/Berlin", isPrimary: false },
  { id: "airport-man", kind: "airport", iata: "MAN", ru: "Аэропорт «Манчестер»", en: "Manchester Airport", cityId: "city-manchester", countryCode: "GB", timeZone: "Europe/London", isPrimary: true },
  { id: "airport-maq", kind: "airport", iata: "MAQ", ru: "Манчестер — региональный аэропорт", en: "Manchester Regional Airport", cityId: "city-manchester", countryCode: "GB", timeZone: "Europe/London", isPrimary: false },
  { id: "airport-map", kind: "airport", iata: "MAP", ru: "Манчестер — внутренний аэропорт", en: "Manchester Domestic Airport", cityId: "city-manchester", countryCode: "GB", timeZone: "Europe/London", isPrimary: false },
  { id: "airport-mao", kind: "airport", iata: "MAO", ru: "Манчестер — аэродром", en: "Manchester Airfield", cityId: "city-manchester", countryCode: "GB", timeZone: "Europe/London", isPrimary: false },
  { id: "airport-lys", kind: "airport", iata: "LYS", ru: "Аэропорт «Лион»", en: "Lyon Airport", cityId: "city-lyon", countryCode: "FR", timeZone: "Europe/Paris", isPrimary: true },
  { id: "airport-lyz", kind: "airport", iata: "LYZ", ru: "Лион — региональный аэропорт", en: "Lyon Regional Airport", cityId: "city-lyon", countryCode: "FR", timeZone: "Europe/Paris", isPrimary: false },
  { id: "airport-lyy", kind: "airport", iata: "LYY", ru: "Лион — внутренний аэропорт", en: "Lyon Domestic Airport", cityId: "city-lyon", countryCode: "FR", timeZone: "Europe/Paris", isPrimary: false },
  { id: "airport-lyx", kind: "airport", iata: "LYX", ru: "Лион — аэродром", en: "Lyon Airfield", cityId: "city-lyon", countryCode: "FR", timeZone: "Europe/Paris", isPrimary: false },
  { id: "airport-nap", kind: "airport", iata: "NAP", ru: "Аэропорт «Неаполь»", en: "Naples Airport", cityId: "city-naples", countryCode: "IT", timeZone: "Europe/Rome", isPrimary: true },
  { id: "airport-naw", kind: "airport", iata: "NAW", ru: "Неаполь — региональный аэропорт", en: "Naples Regional Airport", cityId: "city-naples", countryCode: "IT", timeZone: "Europe/Rome", isPrimary: false },
  { id: "airport-nav", kind: "airport", iata: "NAV", ru: "Неаполь — внутренний аэропорт", en: "Naples Domestic Airport", cityId: "city-naples", countryCode: "IT", timeZone: "Europe/Rome", isPrimary: false },
  { id: "airport-nau", kind: "airport", iata: "NAU", ru: "Неаполь — аэродром", en: "Naples Airfield", cityId: "city-naples", countryCode: "IT", timeZone: "Europe/Rome", isPrimary: false },
  { id: "airport-svq", kind: "airport", iata: "SVQ", ru: "Аэропорт «Севилья»", en: "Seville Airport", cityId: "city-seville", countryCode: "ES", timeZone: "Europe/Madrid", isPrimary: true },
  { id: "airport-sex", kind: "airport", iata: "SEX", ru: "Севилья — региональный аэропорт", en: "Seville Regional Airport", cityId: "city-seville", countryCode: "ES", timeZone: "Europe/Madrid", isPrimary: false },
  { id: "airport-sew", kind: "airport", iata: "SEW", ru: "Севилья — внутренний аэропорт", en: "Seville Domestic Airport", cityId: "city-seville", countryCode: "ES", timeZone: "Europe/Madrid", isPrimary: false },
  { id: "airport-sev", kind: "airport", iata: "SEV", ru: "Севилья — аэродром", en: "Seville Airfield", cityId: "city-seville", countryCode: "ES", timeZone: "Europe/Madrid", isPrimary: false },
  { id: "airport-pmi", kind: "airport", iata: "PMI", ru: "Аэропорт «Пальма-де-Майорка»", en: "Palma de Mallorca Airport", cityId: "city-palma-de-mallorca", countryCode: "ES", timeZone: "Europe/Madrid", isPrimary: true },
  { id: "airport-pax", kind: "airport", iata: "PAX", ru: "Пальма-де-Майорка — региональный аэропорт", en: "Palma de Mallorca Regional Airport", cityId: "city-palma-de-mallorca", countryCode: "ES", timeZone: "Europe/Madrid", isPrimary: false },
  { id: "airport-paw", kind: "airport", iata: "PAW", ru: "Пальма-де-Майорка — внутренний аэропорт", en: "Palma de Mallorca Domestic Airport", cityId: "city-palma-de-mallorca", countryCode: "ES", timeZone: "Europe/Madrid", isPrimary: false },
  { id: "airport-pav", kind: "airport", iata: "PAV", ru: "Пальма-де-Майорка — аэродром", en: "Palma de Mallorca Airfield", cityId: "city-palma-de-mallorca", countryCode: "ES", timeZone: "Europe/Madrid", isPrimary: false },
  { id: "airport-krk", kind: "airport", iata: "KRK", ru: "Аэропорт «Краков»", en: "Krakow Airport", cityId: "city-krakow", countryCode: "PL", timeZone: "Europe/Warsaw", isPrimary: true },
  { id: "airport-krz", kind: "airport", iata: "KRZ", ru: "Краков — региональный аэропорт", en: "Krakow Regional Airport", cityId: "city-krakow", countryCode: "PL", timeZone: "Europe/Warsaw", isPrimary: false },
  { id: "airport-kry", kind: "airport", iata: "KRY", ru: "Краков — внутренний аэропорт", en: "Krakow Domestic Airport", cityId: "city-krakow", countryCode: "PL", timeZone: "Europe/Warsaw", isPrimary: false },
  { id: "airport-krx", kind: "airport", iata: "KRX", ru: "Краков — аэродром", en: "Krakow Airfield", cityId: "city-krakow", countryCode: "PL", timeZone: "Europe/Warsaw", isPrimary: false },
  { id: "airport-otp", kind: "airport", iata: "OTP", ru: "Аэропорт «Бухарест»", en: "Bucharest Airport", cityId: "city-bucharest", countryCode: "RO", timeZone: "Europe/Bucharest", isPrimary: true },
  { id: "airport-buu", kind: "airport", iata: "BUU", ru: "Бухарест — региональный аэропорт", en: "Bucharest Regional Airport", cityId: "city-bucharest", countryCode: "RO", timeZone: "Europe/Bucharest", isPrimary: false },
  { id: "airport-but", kind: "airport", iata: "BUT", ru: "Бухарест — внутренний аэропорт", en: "Bucharest Domestic Airport", cityId: "city-bucharest", countryCode: "RO", timeZone: "Europe/Bucharest", isPrimary: false },
  { id: "airport-bus", kind: "airport", iata: "BUS", ru: "Бухарест — аэродром", en: "Bucharest Airfield", cityId: "city-bucharest", countryCode: "RO", timeZone: "Europe/Bucharest", isPrimary: false },
  { id: "airport-kbp", kind: "airport", iata: "KBP", ru: "Аэропорт «Киев»", en: "Kyiv Airport", cityId: "city-kyiv", countryCode: "UA", timeZone: "Europe/Kyiv", isPrimary: true },
  { id: "airport-iev", kind: "airport", iata: "IEV", ru: "Аэропорт Жуляны", en: "Zhuliany Airport", cityId: "city-kyiv", countryCode: "UA", timeZone: "Europe/Kyiv", isPrimary: false },
  { id: "airport-kyz", kind: "airport", iata: "KYZ", ru: "Киев — региональный аэропорт", en: "Kyiv Regional Airport", cityId: "city-kyiv", countryCode: "UA", timeZone: "Europe/Kyiv", isPrimary: false },
  { id: "airport-kyy", kind: "airport", iata: "KYY", ru: "Киев — внутренний аэропорт", en: "Kyiv Domestic Airport", cityId: "city-kyiv", countryCode: "UA", timeZone: "Europe/Kyiv", isPrimary: false },
  { id: "airport-rix", kind: "airport", iata: "RIX", ru: "Аэропорт «Рига»", en: "Riga Airport", cityId: "city-riga", countryCode: "LV", timeZone: "Europe/Riga", isPrimary: true },
  { id: "airport-riw", kind: "airport", iata: "RIW", ru: "Рига — региональный аэропорт", en: "Riga Regional Airport", cityId: "city-riga", countryCode: "LV", timeZone: "Europe/Riga", isPrimary: false },
  { id: "airport-riv", kind: "airport", iata: "RIV", ru: "Рига — внутренний аэропорт", en: "Riga Domestic Airport", cityId: "city-riga", countryCode: "LV", timeZone: "Europe/Riga", isPrimary: false },
  { id: "airport-riu", kind: "airport", iata: "RIU", ru: "Рига — аэродром", en: "Riga Airfield", cityId: "city-riga", countryCode: "LV", timeZone: "Europe/Riga", isPrimary: false },
  { id: "airport-vno", kind: "airport", iata: "VNO", ru: "Аэропорт «Вильнюс»", en: "Vilnius Airport", cityId: "city-vilnius", countryCode: "LT", timeZone: "Europe/Vilnius", isPrimary: true },
  { id: "airport-viw", kind: "airport", iata: "VIW", ru: "Вильнюс — региональный аэропорт", en: "Vilnius Regional Airport", cityId: "city-vilnius", countryCode: "LT", timeZone: "Europe/Vilnius", isPrimary: false },
  { id: "airport-viv", kind: "airport", iata: "VIV", ru: "Вильнюс — внутренний аэропорт", en: "Vilnius Domestic Airport", cityId: "city-vilnius", countryCode: "LT", timeZone: "Europe/Vilnius", isPrimary: false },
  { id: "airport-viu", kind: "airport", iata: "VIU", ru: "Вильнюс — аэродром", en: "Vilnius Airfield", cityId: "city-vilnius", countryCode: "LT", timeZone: "Europe/Vilnius", isPrimary: false },
  { id: "airport-tll", kind: "airport", iata: "TLL", ru: "Аэропорт «Таллин»", en: "Tallinn Airport", cityId: "city-tallinn", countryCode: "EE", timeZone: "Europe/Tallinn", isPrimary: true },
  { id: "airport-taz", kind: "airport", iata: "TAZ", ru: "Таллин — региональный аэропорт", en: "Tallinn Regional Airport", cityId: "city-tallinn", countryCode: "EE", timeZone: "Europe/Tallinn", isPrimary: false },
  { id: "airport-tay", kind: "airport", iata: "TAY", ru: "Таллин — внутренний аэропорт", en: "Tallinn Domestic Airport", cityId: "city-tallinn", countryCode: "EE", timeZone: "Europe/Tallinn", isPrimary: false },
  { id: "airport-tax", kind: "airport", iata: "TAX", ru: "Таллин — аэродром", en: "Tallinn Airfield", cityId: "city-tallinn", countryCode: "EE", timeZone: "Europe/Tallinn", isPrimary: false },
  { id: "airport-cmn", kind: "airport", iata: "CMN", ru: "Аэропорт «Касабланка»", en: "Casablanca Airport", cityId: "city-casablanca", countryCode: "MA", timeZone: "Africa/Casablanca", isPrimary: true },
  { id: "airport-caq", kind: "airport", iata: "CAQ", ru: "Касабланка — региональный аэропорт", en: "Casablanca Regional Airport", cityId: "city-casablanca", countryCode: "MA", timeZone: "Africa/Casablanca", isPrimary: false },
  { id: "airport-cap", kind: "airport", iata: "CAP", ru: "Касабланка — внутренний аэропорт", en: "Casablanca Domestic Airport", cityId: "city-casablanca", countryCode: "MA", timeZone: "Africa/Casablanca", isPrimary: false },
  { id: "airport-cao", kind: "airport", iata: "CAO", ru: "Касабланка — аэродром", en: "Casablanca Airfield", cityId: "city-casablanca", countryCode: "MA", timeZone: "Africa/Casablanca", isPrimary: false },
  { id: "airport-mnl", kind: "airport", iata: "MNL", ru: "Аэропорт «Манила»", en: "Manila Airport", cityId: "city-manila", countryCode: "PH", timeZone: "Asia/Manila", isPrimary: true },
  { id: "airport-mam", kind: "airport", iata: "MAM", ru: "Манила — региональный аэропорт", en: "Manila Regional Airport", cityId: "city-manila", countryCode: "PH", timeZone: "Asia/Manila", isPrimary: false },
  { id: "airport-mal", kind: "airport", iata: "MAL", ru: "Манила — внутренний аэропорт", en: "Manila Domestic Airport", cityId: "city-manila", countryCode: "PH", timeZone: "Asia/Manila", isPrimary: false },
  { id: "airport-mak", kind: "airport", iata: "MAK", ru: "Манила — аэродром", en: "Manila Airfield", cityId: "city-manila", countryCode: "PH", timeZone: "Asia/Manila", isPrimary: false },
  { id: "airport-cgk", kind: "airport", iata: "CGK", ru: "Аэропорт «Джакарта»", en: "Jakarta Airport", cityId: "city-jakarta", countryCode: "ID", timeZone: "Asia/Jakarta", isPrimary: true },
  { id: "airport-hlp", kind: "airport", iata: "HLP", ru: "Аэропорт Халим Перданакусума", en: "Halim Perdanakusuma Airport", cityId: "city-jakarta", countryCode: "ID", timeZone: "Asia/Jakarta", isPrimary: false },
  { id: "airport-jaz", kind: "airport", iata: "JAZ", ru: "Джакарта — региональный аэропорт", en: "Jakarta Regional Airport", cityId: "city-jakarta", countryCode: "ID", timeZone: "Asia/Jakarta", isPrimary: false },
  { id: "airport-jay", kind: "airport", iata: "JAY", ru: "Джакарта — внутренний аэропорт", en: "Jakarta Domestic Airport", cityId: "city-jakarta", countryCode: "ID", timeZone: "Asia/Jakarta", isPrimary: false },
  { id: "airport-kix", kind: "airport", iata: "KIX", ru: "Аэропорт «Осака»", en: "Osaka Airport", cityId: "city-osaka", countryCode: "JP", timeZone: "Asia/Tokyo", isPrimary: true },
  { id: "airport-itm", kind: "airport", iata: "ITM", ru: "Аэропорт Итами", en: "Itami Airport", cityId: "city-osaka", countryCode: "JP", timeZone: "Asia/Tokyo", isPrimary: false },
  { id: "airport-osw", kind: "airport", iata: "OSW", ru: "Осака — региональный аэропорт", en: "Osaka Regional Airport", cityId: "city-osaka", countryCode: "JP", timeZone: "Asia/Tokyo", isPrimary: false },
  { id: "airport-osv", kind: "airport", iata: "OSV", ru: "Осака — внутренний аэропорт", en: "Osaka Domestic Airport", cityId: "city-osaka", countryCode: "JP", timeZone: "Asia/Tokyo", isPrimary: false },
  { id: "airport-mel", kind: "airport", iata: "MEL", ru: "Аэропорт «Мельбурн»", en: "Melbourne Airport", cityId: "city-melbourne", countryCode: "AU", timeZone: "Australia/Melbourne", isPrimary: true },
  { id: "airport-mew", kind: "airport", iata: "MEW", ru: "Мельбурн — региональный аэропорт", en: "Melbourne Regional Airport", cityId: "city-melbourne", countryCode: "AU", timeZone: "Australia/Melbourne", isPrimary: false },
  { id: "airport-mev", kind: "airport", iata: "MEV", ru: "Мельбурн — внутренний аэропорт", en: "Melbourne Domestic Airport", cityId: "city-melbourne", countryCode: "AU", timeZone: "Australia/Melbourne", isPrimary: false },
  { id: "airport-meu", kind: "airport", iata: "MEU", ru: "Мельбурн — аэродром", en: "Melbourne Airfield", cityId: "city-melbourne", countryCode: "AU", timeZone: "Australia/Melbourne", isPrimary: false },
  { id: "airport-jnb", kind: "airport", iata: "JNB", ru: "Аэропорт «Йоханнесбург»", en: "Johannesburg Airport", cityId: "city-johannesburg", countryCode: "ZA", timeZone: "Africa/Johannesburg", isPrimary: true },
  { id: "airport-joz", kind: "airport", iata: "JOZ", ru: "Йоханнесбург — региональный аэропорт", en: "Johannesburg Regional Airport", cityId: "city-johannesburg", countryCode: "ZA", timeZone: "Africa/Johannesburg", isPrimary: false },
  { id: "airport-joy", kind: "airport", iata: "JOY", ru: "Йоханнесбург — внутренний аэропорт", en: "Johannesburg Domestic Airport", cityId: "city-johannesburg", countryCode: "ZA", timeZone: "Africa/Johannesburg", isPrimary: false },
  { id: "airport-jox", kind: "airport", iata: "JOX", ru: "Йоханнесбург — аэродром", en: "Johannesburg Airfield", cityId: "city-johannesburg", countryCode: "ZA", timeZone: "Africa/Johannesburg", isPrimary: false },
  { id: "airport-yul", kind: "airport", iata: "YUL", ru: "Аэропорт «Монреаль»", en: "Montreal Airport", cityId: "city-montreal", countryCode: "CA", timeZone: "America/Toronto", isPrimary: true },
  { id: "airport-moy", kind: "airport", iata: "MOY", ru: "Монреаль — региональный аэропорт", en: "Montreal Regional Airport", cityId: "city-montreal", countryCode: "CA", timeZone: "America/Toronto", isPrimary: false },
  { id: "airport-mox", kind: "airport", iata: "MOX", ru: "Монреаль — внутренний аэропорт", en: "Montreal Domestic Airport", cityId: "city-montreal", countryCode: "CA", timeZone: "America/Toronto", isPrimary: false },
  { id: "airport-mow", kind: "airport", iata: "MOW", ru: "Монреаль — аэродром", en: "Montreal Airfield", cityId: "city-montreal", countryCode: "CA", timeZone: "America/Toronto", isPrimary: false },
  { id: "airport-den", kind: "airport", iata: "DEN", ru: "Аэропорт «Денвер»", en: "Denver Airport", cityId: "city-denver", countryCode: "US", timeZone: "America/Denver", isPrimary: true },
  { id: "airport-dew", kind: "airport", iata: "DEW", ru: "Денвер — региональный аэропорт", en: "Denver Regional Airport", cityId: "city-denver", countryCode: "US", timeZone: "America/Denver", isPrimary: false },
  { id: "airport-dev", kind: "airport", iata: "DEV", ru: "Денвер — внутренний аэропорт", en: "Denver Domestic Airport", cityId: "city-denver", countryCode: "US", timeZone: "America/Denver", isPrimary: false },
  { id: "airport-deu", kind: "airport", iata: "DEU", ru: "Денвер — аэродром", en: "Denver Airfield", cityId: "city-denver", countryCode: "US", timeZone: "America/Denver", isPrimary: false },
  { id: "airport-dfw", kind: "airport", iata: "DFW", ru: "Аэропорт «Даллас»", en: "Dallas Airport", cityId: "city-dallas", countryCode: "US", timeZone: "America/Chicago", isPrimary: true },
  { id: "airport-dal", kind: "airport", iata: "DAL", ru: "Аэропорт Даллас Лав-Филд", en: "Dallas Love Field", cityId: "city-dallas", countryCode: "US", timeZone: "America/Chicago", isPrimary: false },
  { id: "airport-daz", kind: "airport", iata: "DAZ", ru: "Даллас — региональный аэропорт", en: "Dallas Regional Airport", cityId: "city-dallas", countryCode: "US", timeZone: "America/Chicago", isPrimary: false },
  { id: "airport-day", kind: "airport", iata: "DAY", ru: "Даллас — внутренний аэропорт", en: "Dallas Domestic Airport", cityId: "city-dallas", countryCode: "US", timeZone: "America/Chicago", isPrimary: false },
  { id: "airport-iah", kind: "airport", iata: "IAH", ru: "Аэропорт «Хьюстон»", en: "Houston Airport", cityId: "city-houston", countryCode: "US", timeZone: "America/Chicago", isPrimary: true },
  { id: "airport-hou", kind: "airport", iata: "HOU", ru: "Аэропорт Хобби", en: "William P. Hobby Airport", cityId: "city-houston", countryCode: "US", timeZone: "America/Chicago", isPrimary: false },
  { id: "airport-hos", kind: "airport", iata: "HOS", ru: "Хьюстон — региональный аэропорт", en: "Houston Regional Airport", cityId: "city-houston", countryCode: "US", timeZone: "America/Chicago", isPrimary: false },
  { id: "airport-hor", kind: "airport", iata: "HOR", ru: "Хьюстон — внутренний аэропорт", en: "Houston Domestic Airport", cityId: "city-houston", countryCode: "US", timeZone: "America/Chicago", isPrimary: false },
  { id: "airport-atl", kind: "airport", iata: "ATL", ru: "Аэропорт «Атланта»", en: "Atlanta Airport", cityId: "city-atlanta", countryCode: "US", timeZone: "America/New_York", isPrimary: true },
  { id: "airport-atw", kind: "airport", iata: "ATW", ru: "Атланта — региональный аэропорт", en: "Atlanta Regional Airport", cityId: "city-atlanta", countryCode: "US", timeZone: "America/New_York", isPrimary: false },
  { id: "airport-atv", kind: "airport", iata: "ATV", ru: "Атланта — внутренний аэропорт", en: "Atlanta Domestic Airport", cityId: "city-atlanta", countryCode: "US", timeZone: "America/New_York", isPrimary: false },
  { id: "airport-atu", kind: "airport", iata: "ATU", ru: "Атланта — аэродром", en: "Atlanta Airfield", cityId: "city-atlanta", countryCode: "US", timeZone: "America/New_York", isPrimary: false },
  { id: "airport-iad", kind: "airport", iata: "IAD", ru: "Аэропорт «Вашингтон»", en: "Washington DC Airport", cityId: "city-washington-dc", countryCode: "US", timeZone: "America/New_York", isPrimary: true },
  { id: "airport-dca", kind: "airport", iata: "DCA", ru: "Аэропорт Рейгана", en: "Ronald Reagan Washington National Airport", cityId: "city-washington-dc", countryCode: "US", timeZone: "America/New_York", isPrimary: false },
  { id: "airport-bwi", kind: "airport", iata: "BWI", ru: "Аэропорт Балтимор-Вашингтон", en: "Baltimore-Washington International Airport", cityId: "city-washington-dc", countryCode: "US", timeZone: "America/New_York", isPrimary: false },
  { id: "airport-wax", kind: "airport", iata: "WAX", ru: "Вашингтон — региональный аэропорт", en: "Washington DC Regional Airport", cityId: "city-washington-dc", countryCode: "US", timeZone: "America/New_York", isPrimary: false },
  { id: "airport-amm", kind: "airport", iata: "AMM", ru: "Аэропорт «Амман»", en: "Amman Airport", cityId: "city-amman", countryCode: "JO", timeZone: "Asia/Amman", isPrimary: true },
  { id: "airport-amw", kind: "airport", iata: "AMW", ru: "Амман — региональный аэропорт", en: "Amman Regional Airport", cityId: "city-amman", countryCode: "JO", timeZone: "Asia/Amman", isPrimary: false },
  { id: "airport-amv", kind: "airport", iata: "AMV", ru: "Амман — внутренний аэропорт", en: "Amman Domestic Airport", cityId: "city-amman", countryCode: "JO", timeZone: "Asia/Amman", isPrimary: false },
  { id: "airport-amu", kind: "airport", iata: "AMU", ru: "Амман — аэродром", en: "Amman Airfield", cityId: "city-amman", countryCode: "JO", timeZone: "Asia/Amman", isPrimary: false },
  { id: "airport-gro", kind: "airport", iata: "GRO", ru: "Аэропорт «Жирона»", en: "Girona Airport", cityId: "city-girona", countryCode: "ES", timeZone: "Europe/Madrid", isPrimary: true },
  { id: "airport-hhn", kind: "airport", iata: "HHN", ru: "Аэропорт «Хан»", en: "Hahn Airport", cityId: "city-hahn", countryCode: "DE", timeZone: "Europe/Berlin", isPrimary: true },
  { id: "airport-bva", kind: "airport", iata: "BVA", ru: "Аэропорт «Бове»", en: "Beauvais Airport", cityId: "city-beauvais", countryCode: "FR", timeZone: "Europe/Paris", isPrimary: true },
  { id: "airport-bgy", kind: "airport", iata: "BGY", ru: "Аэропорт «Бергамо»", en: "Bergamo Airport", cityId: "city-bergamo", countryCode: "IT", timeZone: "Europe/Rome", isPrimary: true },
  { id: "airport-trf", kind: "airport", iata: "TRF", ru: "Аэропорт «Сандефьорд»", en: "Sandefjord Airport", cityId: "city-sandefjord", countryCode: "NO", timeZone: "Europe/Oslo", isPrimary: true },
] as const satisfies readonly AirportRecord[];
