import type { PlaceRecord } from "./schema";

/**
 * The place directory: static, curated by hand, deterministic (no API, no generation at runtime).
 * 197 countries (193 UN members + Vatican, Palestine, Taiwan, Hong Kong) and a set of popular cities.
 *
 * Ids are stable FOREVER — they are stored in `trips.place_id`. Format: `country-<iso2 lower>` and
 * `city-<english-name-kebab>`. Never renumber or reuse an id; to retire an entry, keep it (an
 * unknown `place_id` on a stored trip is not an error, but a reused one would show a wrong place).
 *
 * A city carries the ISO alpha-2 code of its country, its IANA time zone and the IATA code of its
 * main airport. A city whose name equals a country's (Singapore, Monaco, Luxembourg, ...) is NOT a
 * separate entry — it would show up twice in suggestions. Multi-airport cities list one main
 * airport (Q5). Integrity (unique ids, IATA shape, valid zones, known country codes) is enforced by
 * `__tests__/directory.test.ts`; the CONTENT (correct IATA/zone per city) is checked by hand.
 *
 * Regions: `middle-east` is separate from `asia`; the Caucasus and Central Asia are `asia`;
 * Türkiye is `middle-east`; Central America and the Caribbean are `north-america`.
 */
export const PLACE_DIRECTORY = [
  // --- Europe ------------------------------------------------------------------------------------
  { id: "country-al", kind: "country", countryCode: "AL", region: "europe", ru: "Албания", en: "Albania" },
  { id: "country-ad", kind: "country", countryCode: "AD", region: "europe", ru: "Андорра", en: "Andorra" },
  { id: "country-at", kind: "country", countryCode: "AT", region: "europe", ru: "Австрия", en: "Austria" },
  { id: "country-by", kind: "country", countryCode: "BY", region: "europe", ru: "Беларусь", en: "Belarus" },
  { id: "country-be", kind: "country", countryCode: "BE", region: "europe", ru: "Бельгия", en: "Belgium" },
  { id: "country-ba", kind: "country", countryCode: "BA", region: "europe", ru: "Босния и Герцеговина", en: "Bosnia and Herzegovina" },
  { id: "country-bg", kind: "country", countryCode: "BG", region: "europe", ru: "Болгария", en: "Bulgaria" },
  { id: "country-hr", kind: "country", countryCode: "HR", region: "europe", ru: "Хорватия", en: "Croatia" },
  { id: "country-cy", kind: "country", countryCode: "CY", region: "europe", ru: "Кипр", en: "Cyprus" },
  { id: "country-cz", kind: "country", countryCode: "CZ", region: "europe", ru: "Чехия", en: "Czechia" },
  { id: "country-dk", kind: "country", countryCode: "DK", region: "europe", ru: "Дания", en: "Denmark" },
  { id: "country-ee", kind: "country", countryCode: "EE", region: "europe", ru: "Эстония", en: "Estonia" },
  { id: "country-fi", kind: "country", countryCode: "FI", region: "europe", ru: "Финляндия", en: "Finland" },
  { id: "country-fr", kind: "country", countryCode: "FR", region: "europe", ru: "Франция", en: "France" },
  { id: "country-de", kind: "country", countryCode: "DE", region: "europe", ru: "Германия", en: "Germany" },
  { id: "country-gr", kind: "country", countryCode: "GR", region: "europe", ru: "Греция", en: "Greece" },
  { id: "country-hu", kind: "country", countryCode: "HU", region: "europe", ru: "Венгрия", en: "Hungary" },
  { id: "country-is", kind: "country", countryCode: "IS", region: "europe", ru: "Исландия", en: "Iceland" },
  { id: "country-ie", kind: "country", countryCode: "IE", region: "europe", ru: "Ирландия", en: "Ireland" },
  { id: "country-it", kind: "country", countryCode: "IT", region: "europe", ru: "Италия", en: "Italy" },
  { id: "country-lv", kind: "country", countryCode: "LV", region: "europe", ru: "Латвия", en: "Latvia" },
  { id: "country-li", kind: "country", countryCode: "LI", region: "europe", ru: "Лихтенштейн", en: "Liechtenstein" },
  { id: "country-lt", kind: "country", countryCode: "LT", region: "europe", ru: "Литва", en: "Lithuania" },
  { id: "country-lu", kind: "country", countryCode: "LU", region: "europe", ru: "Люксембург", en: "Luxembourg" },
  { id: "country-mt", kind: "country", countryCode: "MT", region: "europe", ru: "Мальта", en: "Malta" },
  { id: "country-md", kind: "country", countryCode: "MD", region: "europe", ru: "Молдова", en: "Moldova" },
  { id: "country-mc", kind: "country", countryCode: "MC", region: "europe", ru: "Монако", en: "Monaco" },
  { id: "country-me", kind: "country", countryCode: "ME", region: "europe", ru: "Черногория", en: "Montenegro" },
  { id: "country-nl", kind: "country", countryCode: "NL", region: "europe", ru: "Нидерланды", en: "Netherlands" },
  { id: "country-mk", kind: "country", countryCode: "MK", region: "europe", ru: "Северная Македония", en: "North Macedonia" },
  { id: "country-no", kind: "country", countryCode: "NO", region: "europe", ru: "Норвегия", en: "Norway" },
  { id: "country-pl", kind: "country", countryCode: "PL", region: "europe", ru: "Польша", en: "Poland" },
  { id: "country-pt", kind: "country", countryCode: "PT", region: "europe", ru: "Португалия", en: "Portugal" },
  { id: "country-ro", kind: "country", countryCode: "RO", region: "europe", ru: "Румыния", en: "Romania" },
  { id: "country-ru", kind: "country", countryCode: "RU", region: "europe", ru: "Россия", en: "Russia" },
  { id: "country-sm", kind: "country", countryCode: "SM", region: "europe", ru: "Сан-Марино", en: "San Marino" },
  { id: "country-rs", kind: "country", countryCode: "RS", region: "europe", ru: "Сербия", en: "Serbia" },
  { id: "country-sk", kind: "country", countryCode: "SK", region: "europe", ru: "Словакия", en: "Slovakia" },
  { id: "country-si", kind: "country", countryCode: "SI", region: "europe", ru: "Словения", en: "Slovenia" },
  { id: "country-es", kind: "country", countryCode: "ES", region: "europe", ru: "Испания", en: "Spain" },
  { id: "country-se", kind: "country", countryCode: "SE", region: "europe", ru: "Швеция", en: "Sweden" },
  { id: "country-ch", kind: "country", countryCode: "CH", region: "europe", ru: "Швейцария", en: "Switzerland" },
  { id: "country-ua", kind: "country", countryCode: "UA", region: "europe", ru: "Украина", en: "Ukraine" },
  { id: "country-gb", kind: "country", countryCode: "GB", region: "europe", ru: "Великобритания", en: "United Kingdom" },
  { id: "country-va", kind: "country", countryCode: "VA", region: "europe", ru: "Ватикан", en: "Vatican City" },

  // --- Asia --------------------------------------------------------------------------------------
  { id: "country-af", kind: "country", countryCode: "AF", region: "asia", ru: "Афганистан", en: "Afghanistan" },
  { id: "country-am", kind: "country", countryCode: "AM", region: "asia", ru: "Армения", en: "Armenia" },
  { id: "country-az", kind: "country", countryCode: "AZ", region: "asia", ru: "Азербайджан", en: "Azerbaijan" },
  { id: "country-bd", kind: "country", countryCode: "BD", region: "asia", ru: "Бангладеш", en: "Bangladesh" },
  { id: "country-bt", kind: "country", countryCode: "BT", region: "asia", ru: "Бутан", en: "Bhutan" },
  { id: "country-bn", kind: "country", countryCode: "BN", region: "asia", ru: "Бруней", en: "Brunei" },
  { id: "country-kh", kind: "country", countryCode: "KH", region: "asia", ru: "Камбоджа", en: "Cambodia" },
  { id: "country-cn", kind: "country", countryCode: "CN", region: "asia", ru: "Китай", en: "China" },
  { id: "country-ge", kind: "country", countryCode: "GE", region: "asia", ru: "Грузия", en: "Georgia" },
  { id: "country-hk", kind: "country", countryCode: "HK", region: "asia", ru: "Гонконг", en: "Hong Kong" },
  { id: "country-in", kind: "country", countryCode: "IN", region: "asia", ru: "Индия", en: "India" },
  { id: "country-id", kind: "country", countryCode: "ID", region: "asia", ru: "Индонезия", en: "Indonesia" },
  { id: "country-jp", kind: "country", countryCode: "JP", region: "asia", ru: "Япония", en: "Japan" },
  { id: "country-kz", kind: "country", countryCode: "KZ", region: "asia", ru: "Казахстан", en: "Kazakhstan" },
  { id: "country-kg", kind: "country", countryCode: "KG", region: "asia", ru: "Киргизия", en: "Kyrgyzstan" },
  { id: "country-la", kind: "country", countryCode: "LA", region: "asia", ru: "Лаос", en: "Laos" },
  { id: "country-my", kind: "country", countryCode: "MY", region: "asia", ru: "Малайзия", en: "Malaysia" },
  { id: "country-mv", kind: "country", countryCode: "MV", region: "asia", ru: "Мальдивы", en: "Maldives" },
  { id: "country-mn", kind: "country", countryCode: "MN", region: "asia", ru: "Монголия", en: "Mongolia" },
  { id: "country-mm", kind: "country", countryCode: "MM", region: "asia", ru: "Мьянма", en: "Myanmar" },
  { id: "country-np", kind: "country", countryCode: "NP", region: "asia", ru: "Непал", en: "Nepal" },
  { id: "country-kp", kind: "country", countryCode: "KP", region: "asia", ru: "Северная Корея", en: "North Korea" },
  { id: "country-pk", kind: "country", countryCode: "PK", region: "asia", ru: "Пакистан", en: "Pakistan" },
  { id: "country-ph", kind: "country", countryCode: "PH", region: "asia", ru: "Филиппины", en: "Philippines" },
  { id: "country-sg", kind: "country", countryCode: "SG", region: "asia", ru: "Сингапур", en: "Singapore" },
  { id: "country-kr", kind: "country", countryCode: "KR", region: "asia", ru: "Южная Корея", en: "South Korea" },
  { id: "country-lk", kind: "country", countryCode: "LK", region: "asia", ru: "Шри-Ланка", en: "Sri Lanka" },
  { id: "country-tw", kind: "country", countryCode: "TW", region: "asia", ru: "Тайвань", en: "Taiwan" },
  { id: "country-tj", kind: "country", countryCode: "TJ", region: "asia", ru: "Таджикистан", en: "Tajikistan" },
  { id: "country-th", kind: "country", countryCode: "TH", region: "asia", ru: "Таиланд", en: "Thailand" },
  { id: "country-tl", kind: "country", countryCode: "TL", region: "asia", ru: "Восточный Тимор", en: "Timor-Leste" },
  { id: "country-tm", kind: "country", countryCode: "TM", region: "asia", ru: "Туркмения", en: "Turkmenistan" },
  { id: "country-uz", kind: "country", countryCode: "UZ", region: "asia", ru: "Узбекистан", en: "Uzbekistan" },
  { id: "country-vn", kind: "country", countryCode: "VN", region: "asia", ru: "Вьетнам", en: "Vietnam" },

  // --- Middle East -------------------------------------------------------------------------------
  { id: "country-bh", kind: "country", countryCode: "BH", region: "middle-east", ru: "Бахрейн", en: "Bahrain" },
  { id: "country-ir", kind: "country", countryCode: "IR", region: "middle-east", ru: "Иран", en: "Iran" },
  { id: "country-iq", kind: "country", countryCode: "IQ", region: "middle-east", ru: "Ирак", en: "Iraq" },
  { id: "country-il", kind: "country", countryCode: "IL", region: "middle-east", ru: "Израиль", en: "Israel" },
  { id: "country-jo", kind: "country", countryCode: "JO", region: "middle-east", ru: "Иордания", en: "Jordan" },
  { id: "country-kw", kind: "country", countryCode: "KW", region: "middle-east", ru: "Кувейт", en: "Kuwait" },
  { id: "country-lb", kind: "country", countryCode: "LB", region: "middle-east", ru: "Ливан", en: "Lebanon" },
  { id: "country-om", kind: "country", countryCode: "OM", region: "middle-east", ru: "Оман", en: "Oman" },
  { id: "country-ps", kind: "country", countryCode: "PS", region: "middle-east", ru: "Палестина", en: "Palestine" },
  { id: "country-qa", kind: "country", countryCode: "QA", region: "middle-east", ru: "Катар", en: "Qatar" },
  { id: "country-sa", kind: "country", countryCode: "SA", region: "middle-east", ru: "Саудовская Аравия", en: "Saudi Arabia" },
  { id: "country-sy", kind: "country", countryCode: "SY", region: "middle-east", ru: "Сирия", en: "Syria" },
  { id: "country-tr", kind: "country", countryCode: "TR", region: "middle-east", ru: "Турция", en: "Turkey" },
  { id: "country-ae", kind: "country", countryCode: "AE", region: "middle-east", ru: "ОАЭ", en: "United Arab Emirates" },
  { id: "country-ye", kind: "country", countryCode: "YE", region: "middle-east", ru: "Йемен", en: "Yemen" },

  // --- Africa ------------------------------------------------------------------------------------
  { id: "country-dz", kind: "country", countryCode: "DZ", region: "africa", ru: "Алжир", en: "Algeria" },
  { id: "country-ao", kind: "country", countryCode: "AO", region: "africa", ru: "Ангола", en: "Angola" },
  { id: "country-bj", kind: "country", countryCode: "BJ", region: "africa", ru: "Бенин", en: "Benin" },
  { id: "country-bw", kind: "country", countryCode: "BW", region: "africa", ru: "Ботсвана", en: "Botswana" },
  { id: "country-bf", kind: "country", countryCode: "BF", region: "africa", ru: "Буркина-Фасо", en: "Burkina Faso" },
  { id: "country-bi", kind: "country", countryCode: "BI", region: "africa", ru: "Бурунди", en: "Burundi" },
  { id: "country-cv", kind: "country", countryCode: "CV", region: "africa", ru: "Кабо-Верде", en: "Cabo Verde" },
  { id: "country-cm", kind: "country", countryCode: "CM", region: "africa", ru: "Камерун", en: "Cameroon" },
  { id: "country-cf", kind: "country", countryCode: "CF", region: "africa", ru: "Центральноафриканская Республика", en: "Central African Republic" },
  { id: "country-td", kind: "country", countryCode: "TD", region: "africa", ru: "Чад", en: "Chad" },
  { id: "country-km", kind: "country", countryCode: "KM", region: "africa", ru: "Коморы", en: "Comoros" },
  { id: "country-cg", kind: "country", countryCode: "CG", region: "africa", ru: "Конго", en: "Congo" },
  { id: "country-cd", kind: "country", countryCode: "CD", region: "africa", ru: "Демократическая Республика Конго", en: "Democratic Republic of the Congo" },
  { id: "country-ci", kind: "country", countryCode: "CI", region: "africa", ru: "Кот-д’Ивуар", en: "Côte d’Ivoire" },
  { id: "country-dj", kind: "country", countryCode: "DJ", region: "africa", ru: "Джибути", en: "Djibouti" },
  { id: "country-eg", kind: "country", countryCode: "EG", region: "africa", ru: "Египет", en: "Egypt" },
  { id: "country-gq", kind: "country", countryCode: "GQ", region: "africa", ru: "Экваториальная Гвинея", en: "Equatorial Guinea" },
  { id: "country-er", kind: "country", countryCode: "ER", region: "africa", ru: "Эритрея", en: "Eritrea" },
  { id: "country-sz", kind: "country", countryCode: "SZ", region: "africa", ru: "Эсватини", en: "Eswatini" },
  { id: "country-et", kind: "country", countryCode: "ET", region: "africa", ru: "Эфиопия", en: "Ethiopia" },
  { id: "country-ga", kind: "country", countryCode: "GA", region: "africa", ru: "Габон", en: "Gabon" },
  { id: "country-gm", kind: "country", countryCode: "GM", region: "africa", ru: "Гамбия", en: "Gambia" },
  { id: "country-gh", kind: "country", countryCode: "GH", region: "africa", ru: "Гана", en: "Ghana" },
  { id: "country-gn", kind: "country", countryCode: "GN", region: "africa", ru: "Гвинея", en: "Guinea" },
  { id: "country-gw", kind: "country", countryCode: "GW", region: "africa", ru: "Гвинея-Бисау", en: "Guinea-Bissau" },
  { id: "country-ke", kind: "country", countryCode: "KE", region: "africa", ru: "Кения", en: "Kenya" },
  { id: "country-ls", kind: "country", countryCode: "LS", region: "africa", ru: "Лесото", en: "Lesotho" },
  { id: "country-lr", kind: "country", countryCode: "LR", region: "africa", ru: "Либерия", en: "Liberia" },
  { id: "country-ly", kind: "country", countryCode: "LY", region: "africa", ru: "Ливия", en: "Libya" },
  { id: "country-mg", kind: "country", countryCode: "MG", region: "africa", ru: "Мадагаскар", en: "Madagascar" },
  { id: "country-mw", kind: "country", countryCode: "MW", region: "africa", ru: "Малави", en: "Malawi" },
  { id: "country-ml", kind: "country", countryCode: "ML", region: "africa", ru: "Мали", en: "Mali" },
  { id: "country-mr", kind: "country", countryCode: "MR", region: "africa", ru: "Мавритания", en: "Mauritania" },
  { id: "country-mu", kind: "country", countryCode: "MU", region: "africa", ru: "Маврикий", en: "Mauritius" },
  { id: "country-ma", kind: "country", countryCode: "MA", region: "africa", ru: "Марокко", en: "Morocco" },
  { id: "country-mz", kind: "country", countryCode: "MZ", region: "africa", ru: "Мозамбик", en: "Mozambique" },
  { id: "country-na", kind: "country", countryCode: "NA", region: "africa", ru: "Намибия", en: "Namibia" },
  { id: "country-ne", kind: "country", countryCode: "NE", region: "africa", ru: "Нигер", en: "Niger" },
  { id: "country-ng", kind: "country", countryCode: "NG", region: "africa", ru: "Нигерия", en: "Nigeria" },
  { id: "country-rw", kind: "country", countryCode: "RW", region: "africa", ru: "Руанда", en: "Rwanda" },
  { id: "country-st", kind: "country", countryCode: "ST", region: "africa", ru: "Сан-Томе и Принсипи", en: "São Tomé and Príncipe" },
  { id: "country-sn", kind: "country", countryCode: "SN", region: "africa", ru: "Сенегал", en: "Senegal" },
  { id: "country-sc", kind: "country", countryCode: "SC", region: "africa", ru: "Сейшелы", en: "Seychelles" },
  { id: "country-sl", kind: "country", countryCode: "SL", region: "africa", ru: "Сьерра-Леоне", en: "Sierra Leone" },
  { id: "country-so", kind: "country", countryCode: "SO", region: "africa", ru: "Сомали", en: "Somalia" },
  { id: "country-za", kind: "country", countryCode: "ZA", region: "africa", ru: "ЮАР", en: "South Africa" },
  { id: "country-ss", kind: "country", countryCode: "SS", region: "africa", ru: "Южный Судан", en: "South Sudan" },
  { id: "country-sd", kind: "country", countryCode: "SD", region: "africa", ru: "Судан", en: "Sudan" },
  { id: "country-tz", kind: "country", countryCode: "TZ", region: "africa", ru: "Танзания", en: "Tanzania" },
  { id: "country-tg", kind: "country", countryCode: "TG", region: "africa", ru: "Того", en: "Togo" },
  { id: "country-tn", kind: "country", countryCode: "TN", region: "africa", ru: "Тунис", en: "Tunisia" },
  { id: "country-ug", kind: "country", countryCode: "UG", region: "africa", ru: "Уганда", en: "Uganda" },
  { id: "country-zm", kind: "country", countryCode: "ZM", region: "africa", ru: "Замбия", en: "Zambia" },
  { id: "country-zw", kind: "country", countryCode: "ZW", region: "africa", ru: "Зимбабве", en: "Zimbabwe" },

  // --- North America, Central America, Caribbean -------------------------------------------------
  { id: "country-ag", kind: "country", countryCode: "AG", region: "north-america", ru: "Антигуа и Барбуда", en: "Antigua and Barbuda" },
  { id: "country-bs", kind: "country", countryCode: "BS", region: "north-america", ru: "Багамы", en: "Bahamas" },
  { id: "country-bb", kind: "country", countryCode: "BB", region: "north-america", ru: "Барбадос", en: "Barbados" },
  { id: "country-bz", kind: "country", countryCode: "BZ", region: "north-america", ru: "Белиз", en: "Belize" },
  { id: "country-ca", kind: "country", countryCode: "CA", region: "north-america", ru: "Канада", en: "Canada" },
  { id: "country-cr", kind: "country", countryCode: "CR", region: "north-america", ru: "Коста-Рика", en: "Costa Rica" },
  { id: "country-cu", kind: "country", countryCode: "CU", region: "north-america", ru: "Куба", en: "Cuba" },
  { id: "country-dm", kind: "country", countryCode: "DM", region: "north-america", ru: "Доминика", en: "Dominica" },
  { id: "country-do", kind: "country", countryCode: "DO", region: "north-america", ru: "Доминикана", en: "Dominican Republic" },
  { id: "country-sv", kind: "country", countryCode: "SV", region: "north-america", ru: "Сальвадор", en: "El Salvador" },
  { id: "country-gd", kind: "country", countryCode: "GD", region: "north-america", ru: "Гренада", en: "Grenada" },
  { id: "country-gt", kind: "country", countryCode: "GT", region: "north-america", ru: "Гватемала", en: "Guatemala" },
  { id: "country-ht", kind: "country", countryCode: "HT", region: "north-america", ru: "Гаити", en: "Haiti" },
  { id: "country-hn", kind: "country", countryCode: "HN", region: "north-america", ru: "Гондурас", en: "Honduras" },
  { id: "country-jm", kind: "country", countryCode: "JM", region: "north-america", ru: "Ямайка", en: "Jamaica" },
  { id: "country-mx", kind: "country", countryCode: "MX", region: "north-america", ru: "Мексика", en: "Mexico" },
  { id: "country-ni", kind: "country", countryCode: "NI", region: "north-america", ru: "Никарагуа", en: "Nicaragua" },
  { id: "country-pa", kind: "country", countryCode: "PA", region: "north-america", ru: "Панама", en: "Panama" },
  { id: "country-kn", kind: "country", countryCode: "KN", region: "north-america", ru: "Сент-Китс и Невис", en: "Saint Kitts and Nevis" },
  { id: "country-lc", kind: "country", countryCode: "LC", region: "north-america", ru: "Сент-Люсия", en: "Saint Lucia" },
  { id: "country-vc", kind: "country", countryCode: "VC", region: "north-america", ru: "Сент-Винсент и Гренадины", en: "Saint Vincent and the Grenadines" },
  { id: "country-tt", kind: "country", countryCode: "TT", region: "north-america", ru: "Тринидад и Тобаго", en: "Trinidad and Tobago" },
  { id: "country-us", kind: "country", countryCode: "US", region: "north-america", ru: "США", en: "United States" },

  // --- South America -----------------------------------------------------------------------------
  { id: "country-ar", kind: "country", countryCode: "AR", region: "south-america", ru: "Аргентина", en: "Argentina" },
  { id: "country-bo", kind: "country", countryCode: "BO", region: "south-america", ru: "Боливия", en: "Bolivia" },
  { id: "country-br", kind: "country", countryCode: "BR", region: "south-america", ru: "Бразилия", en: "Brazil" },
  { id: "country-cl", kind: "country", countryCode: "CL", region: "south-america", ru: "Чили", en: "Chile" },
  { id: "country-co", kind: "country", countryCode: "CO", region: "south-america", ru: "Колумбия", en: "Colombia" },
  { id: "country-ec", kind: "country", countryCode: "EC", region: "south-america", ru: "Эквадор", en: "Ecuador" },
  { id: "country-gy", kind: "country", countryCode: "GY", region: "south-america", ru: "Гайана", en: "Guyana" },
  { id: "country-py", kind: "country", countryCode: "PY", region: "south-america", ru: "Парагвай", en: "Paraguay" },
  { id: "country-pe", kind: "country", countryCode: "PE", region: "south-america", ru: "Перу", en: "Peru" },
  { id: "country-sr", kind: "country", countryCode: "SR", region: "south-america", ru: "Суринам", en: "Suriname" },
  { id: "country-uy", kind: "country", countryCode: "UY", region: "south-america", ru: "Уругвай", en: "Uruguay" },
  { id: "country-ve", kind: "country", countryCode: "VE", region: "south-america", ru: "Венесуэла", en: "Venezuela" },

  // --- Oceania -----------------------------------------------------------------------------------
  { id: "country-au", kind: "country", countryCode: "AU", region: "oceania", ru: "Австралия", en: "Australia" },
  { id: "country-fj", kind: "country", countryCode: "FJ", region: "oceania", ru: "Фиджи", en: "Fiji" },
  { id: "country-ki", kind: "country", countryCode: "KI", region: "oceania", ru: "Кирибати", en: "Kiribati" },
  { id: "country-mh", kind: "country", countryCode: "MH", region: "oceania", ru: "Маршалловы Острова", en: "Marshall Islands" },
  { id: "country-fm", kind: "country", countryCode: "FM", region: "oceania", ru: "Микронезия", en: "Micronesia" },
  { id: "country-nr", kind: "country", countryCode: "NR", region: "oceania", ru: "Науру", en: "Nauru" },
  { id: "country-nz", kind: "country", countryCode: "NZ", region: "oceania", ru: "Новая Зеландия", en: "New Zealand" },
  { id: "country-pw", kind: "country", countryCode: "PW", region: "oceania", ru: "Палау", en: "Palau" },
  { id: "country-pg", kind: "country", countryCode: "PG", region: "oceania", ru: "Папуа — Новая Гвинея", en: "Papua New Guinea" },
  { id: "country-ws", kind: "country", countryCode: "WS", region: "oceania", ru: "Самоа", en: "Samoa" },
  { id: "country-sb", kind: "country", countryCode: "SB", region: "oceania", ru: "Соломоновы Острова", en: "Solomon Islands" },
  { id: "country-to", kind: "country", countryCode: "TO", region: "oceania", ru: "Тонга", en: "Tonga" },
  { id: "country-tv", kind: "country", countryCode: "TV", region: "oceania", ru: "Тувалу", en: "Tuvalu" },
  { id: "country-vu", kind: "country", countryCode: "VU", region: "oceania", ru: "Вануату", en: "Vanuatu" },

  // --- Cities: Europe ----------------------------------------------------------------------------
  { id: "city-lisbon", kind: "city", ru: "Лиссабон", en: "Lisbon", countryCode: "PT", timeZone: "Europe/Lisbon", airportCode: "LIS" },
  { id: "city-porto", kind: "city", ru: "Порту", en: "Porto", countryCode: "PT", timeZone: "Europe/Lisbon", airportCode: "OPO" },
  { id: "city-madrid", kind: "city", ru: "Мадрид", en: "Madrid", countryCode: "ES", timeZone: "Europe/Madrid", airportCode: "MAD" },
  { id: "city-barcelona", kind: "city", ru: "Барселона", en: "Barcelona", countryCode: "ES", timeZone: "Europe/Madrid", airportCode: "BCN" },
  { id: "city-paris", kind: "city", ru: "Париж", en: "Paris", countryCode: "FR", timeZone: "Europe/Paris", airportCode: "CDG" },
  { id: "city-nice", kind: "city", ru: "Ницца", en: "Nice", countryCode: "FR", timeZone: "Europe/Paris", airportCode: "NCE" },
  { id: "city-rome", kind: "city", ru: "Рим", en: "Rome", countryCode: "IT", timeZone: "Europe/Rome", airportCode: "FCO" },
  { id: "city-milan", kind: "city", ru: "Милан", en: "Milan", countryCode: "IT", timeZone: "Europe/Rome", airportCode: "MXP" },
  { id: "city-venice", kind: "city", ru: "Венеция", en: "Venice", countryCode: "IT", timeZone: "Europe/Rome", airportCode: "VCE" },
  { id: "city-florence", kind: "city", ru: "Флоренция", en: "Florence", countryCode: "IT", timeZone: "Europe/Rome", airportCode: "FLR" },
  { id: "city-berlin", kind: "city", ru: "Берлин", en: "Berlin", countryCode: "DE", timeZone: "Europe/Berlin", airportCode: "BER" },
  { id: "city-munich", kind: "city", ru: "Мюнхен", en: "Munich", countryCode: "DE", timeZone: "Europe/Berlin", airportCode: "MUC" },
  { id: "city-london", kind: "city", ru: "Лондон", en: "London", countryCode: "GB", timeZone: "Europe/London", airportCode: "LHR" },
  { id: "city-dublin", kind: "city", ru: "Дублин", en: "Dublin", countryCode: "IE", timeZone: "Europe/Dublin", airportCode: "DUB" },
  { id: "city-amsterdam", kind: "city", ru: "Амстердам", en: "Amsterdam", countryCode: "NL", timeZone: "Europe/Amsterdam", airportCode: "AMS" },
  { id: "city-brussels", kind: "city", ru: "Брюссель", en: "Brussels", countryCode: "BE", timeZone: "Europe/Brussels", airportCode: "BRU" },
  { id: "city-zurich", kind: "city", ru: "Цюрих", en: "Zürich", countryCode: "CH", timeZone: "Europe/Zurich", airportCode: "ZRH" },
  { id: "city-geneva", kind: "city", ru: "Женева", en: "Geneva", countryCode: "CH", timeZone: "Europe/Zurich", airportCode: "GVA" },
  { id: "city-vienna", kind: "city", ru: "Вена", en: "Vienna", countryCode: "AT", timeZone: "Europe/Vienna", airportCode: "VIE" },
  { id: "city-prague", kind: "city", ru: "Прага", en: "Prague", countryCode: "CZ", timeZone: "Europe/Prague", airportCode: "PRG" },
  { id: "city-budapest", kind: "city", ru: "Будапешт", en: "Budapest", countryCode: "HU", timeZone: "Europe/Budapest", airportCode: "BUD" },
  { id: "city-warsaw", kind: "city", ru: "Варшава", en: "Warsaw", countryCode: "PL", timeZone: "Europe/Warsaw", airportCode: "WAW" },
  { id: "city-athens", kind: "city", ru: "Афины", en: "Athens", countryCode: "GR", timeZone: "Europe/Athens", airportCode: "ATH" },
  { id: "city-dubrovnik", kind: "city", ru: "Дубровник", en: "Dubrovnik", countryCode: "HR", timeZone: "Europe/Zagreb", airportCode: "DBV" },
  { id: "city-istanbul", kind: "city", ru: "Стамбул", en: "Istanbul", countryCode: "TR", timeZone: "Europe/Istanbul", airportCode: "IST" },
  { id: "city-moscow", kind: "city", ru: "Москва", en: "Moscow", countryCode: "RU", timeZone: "Europe/Moscow", airportCode: "SVO" },
  { id: "city-saint-petersburg", kind: "city", ru: "Санкт-Петербург", en: "Saint Petersburg", countryCode: "RU", timeZone: "Europe/Moscow", airportCode: "LED" },
  { id: "city-copenhagen", kind: "city", ru: "Копенгаген", en: "Copenhagen", countryCode: "DK", timeZone: "Europe/Copenhagen", airportCode: "CPH" },
  { id: "city-stockholm", kind: "city", ru: "Стокгольм", en: "Stockholm", countryCode: "SE", timeZone: "Europe/Stockholm", airportCode: "ARN" },
  { id: "city-oslo", kind: "city", ru: "Осло", en: "Oslo", countryCode: "NO", timeZone: "Europe/Oslo", airportCode: "OSL" },
  { id: "city-helsinki", kind: "city", ru: "Хельсинки", en: "Helsinki", countryCode: "FI", timeZone: "Europe/Helsinki", airportCode: "HEL" },
  { id: "city-reykjavik", kind: "city", ru: "Рейкьявик", en: "Reykjavik", countryCode: "IS", timeZone: "Atlantic/Reykjavik", airportCode: "KEF" },

  // --- Cities: Middle East, Africa, Asia, Oceania ------------------------------------------------
  { id: "city-dubai", kind: "city", ru: "Дубай", en: "Dubai", countryCode: "AE", timeZone: "Asia/Dubai", airportCode: "DXB" },
  { id: "city-doha", kind: "city", ru: "Доха", en: "Doha", countryCode: "QA", timeZone: "Asia/Qatar", airportCode: "DOH" },
  { id: "city-tel-aviv", kind: "city", ru: "Тель-Авив", en: "Tel Aviv", countryCode: "IL", timeZone: "Asia/Jerusalem", airportCode: "TLV" },
  { id: "city-cairo", kind: "city", ru: "Каир", en: "Cairo", countryCode: "EG", timeZone: "Africa/Cairo", airportCode: "CAI" },
  { id: "city-marrakesh", kind: "city", ru: "Марракеш", en: "Marrakesh", countryCode: "MA", timeZone: "Africa/Casablanca", airportCode: "RAK" },
  { id: "city-cape-town", kind: "city", ru: "Кейптаун", en: "Cape Town", countryCode: "ZA", timeZone: "Africa/Johannesburg", airportCode: "CPT" },
  { id: "city-nairobi", kind: "city", ru: "Найроби", en: "Nairobi", countryCode: "KE", timeZone: "Africa/Nairobi", airportCode: "NBO" },
  { id: "city-tbilisi", kind: "city", ru: "Тбилиси", en: "Tbilisi", countryCode: "GE", timeZone: "Asia/Tbilisi", airportCode: "TBS" },
  { id: "city-yerevan", kind: "city", ru: "Ереван", en: "Yerevan", countryCode: "AM", timeZone: "Asia/Yerevan", airportCode: "EVN" },
  { id: "city-bangkok", kind: "city", ru: "Бангкок", en: "Bangkok", countryCode: "TH", timeZone: "Asia/Bangkok", airportCode: "BKK" },
  { id: "city-phuket", kind: "city", ru: "Пхукет", en: "Phuket", countryCode: "TH", timeZone: "Asia/Bangkok", airportCode: "HKT" },
  { id: "city-bali", kind: "city", ru: "Бали", en: "Bali", countryCode: "ID", timeZone: "Asia/Makassar", airportCode: "DPS" },
  { id: "city-ho-chi-minh-city", kind: "city", ru: "Хошимин", en: "Ho Chi Minh City", countryCode: "VN", timeZone: "Asia/Ho_Chi_Minh", airportCode: "SGN" },
  { id: "city-kuala-lumpur", kind: "city", ru: "Куала-Лумпур", en: "Kuala Lumpur", countryCode: "MY", timeZone: "Asia/Kuala_Lumpur", airportCode: "KUL" },
  { id: "city-male", kind: "city", ru: "Мале", en: "Malé", countryCode: "MV", timeZone: "Indian/Maldives", airportCode: "MLE" },
  { id: "city-delhi", kind: "city", ru: "Дели", en: "Delhi", countryCode: "IN", timeZone: "Asia/Kolkata", airportCode: "DEL" },
  { id: "city-beijing", kind: "city", ru: "Пекин", en: "Beijing", countryCode: "CN", timeZone: "Asia/Shanghai", airportCode: "PEK" },
  { id: "city-shanghai", kind: "city", ru: "Шанхай", en: "Shanghai", countryCode: "CN", timeZone: "Asia/Shanghai", airportCode: "PVG" },
  { id: "city-tokyo", kind: "city", ru: "Токио", en: "Tokyo", countryCode: "JP", timeZone: "Asia/Tokyo", airportCode: "HND" },
  { id: "city-seoul", kind: "city", ru: "Сеул", en: "Seoul", countryCode: "KR", timeZone: "Asia/Seoul", airportCode: "ICN" },
  { id: "city-sydney", kind: "city", ru: "Сидней", en: "Sydney", countryCode: "AU", timeZone: "Australia/Sydney", airportCode: "SYD" },
  { id: "city-auckland", kind: "city", ru: "Окленд", en: "Auckland", countryCode: "NZ", timeZone: "Pacific/Auckland", airportCode: "AKL" },

  // --- Cities: the Americas ----------------------------------------------------------------------
  { id: "city-new-york", kind: "city", ru: "Нью-Йорк", en: "New York", countryCode: "US", timeZone: "America/New_York", airportCode: "JFK" },
  { id: "city-los-angeles", kind: "city", ru: "Лос-Анджелес", en: "Los Angeles", countryCode: "US", timeZone: "America/Los_Angeles", airportCode: "LAX" },
  { id: "city-san-francisco", kind: "city", ru: "Сан-Франциско", en: "San Francisco", countryCode: "US", timeZone: "America/Los_Angeles", airportCode: "SFO" },
  { id: "city-miami", kind: "city", ru: "Майами", en: "Miami", countryCode: "US", timeZone: "America/New_York", airportCode: "MIA" },
  { id: "city-chicago", kind: "city", ru: "Чикаго", en: "Chicago", countryCode: "US", timeZone: "America/Chicago", airportCode: "ORD" },
  { id: "city-honolulu", kind: "city", ru: "Гонолулу", en: "Honolulu", countryCode: "US", timeZone: "Pacific/Honolulu", airportCode: "HNL" },
  { id: "city-toronto", kind: "city", ru: "Торонто", en: "Toronto", countryCode: "CA", timeZone: "America/Toronto", airportCode: "YYZ" },
  { id: "city-vancouver", kind: "city", ru: "Ванкувер", en: "Vancouver", countryCode: "CA", timeZone: "America/Vancouver", airportCode: "YVR" },
  { id: "city-mexico-city", kind: "city", ru: "Мехико", en: "Mexico City", countryCode: "MX", timeZone: "America/Mexico_City", airportCode: "MEX" },
  { id: "city-cancun", kind: "city", ru: "Канкун", en: "Cancún", countryCode: "MX", timeZone: "America/Cancun", airportCode: "CUN" },
  { id: "city-rio-de-janeiro", kind: "city", ru: "Рио-де-Жанейро", en: "Rio de Janeiro", countryCode: "BR", timeZone: "America/Sao_Paulo", airportCode: "GIG" },
  { id: "city-sao-paulo", kind: "city", ru: "Сан-Паулу", en: "São Paulo", countryCode: "BR", timeZone: "America/Sao_Paulo", airportCode: "GRU" },
  { id: "city-buenos-aires", kind: "city", ru: "Буэнос-Айрес", en: "Buenos Aires", countryCode: "AR", timeZone: "America/Argentina/Buenos_Aires", airportCode: "EZE" },
  { id: "city-lima", kind: "city", ru: "Лима", en: "Lima", countryCode: "PE", timeZone: "America/Lima", airportCode: "LIM" },
  { id: "city-bogota", kind: "city", ru: "Богота", en: "Bogotá", countryCode: "CO", timeZone: "America/Bogota", airportCode: "BOG" },
  { id: "city-santiago", kind: "city", ru: "Сантьяго", en: "Santiago", countryCode: "CL", timeZone: "America/Santiago", airportCode: "SCL" },

  // --- Cities: more airport hubs (SPEC-04, PLAN-04 step 2) ----------------------------------------
  { id: "city-frankfurt", kind: "city", ru: "Франкфурт-на-Майне", en: "Frankfurt", countryCode: "DE", timeZone: "Europe/Berlin", airportCode: "FRA" },
  { id: "city-manchester", kind: "city", ru: "Манчестер", en: "Manchester", countryCode: "GB", timeZone: "Europe/London", airportCode: "MAN" },
  { id: "city-lyon", kind: "city", ru: "Лион", en: "Lyon", countryCode: "FR", timeZone: "Europe/Paris", airportCode: "LYS" },
  { id: "city-naples", kind: "city", ru: "Неаполь", en: "Naples", countryCode: "IT", timeZone: "Europe/Rome", airportCode: "NAP" },
  { id: "city-seville", kind: "city", ru: "Севилья", en: "Seville", countryCode: "ES", timeZone: "Europe/Madrid", airportCode: "SVQ" },
  { id: "city-palma-de-mallorca", kind: "city", ru: "Пальма-де-Майорка", en: "Palma de Mallorca", countryCode: "ES", timeZone: "Europe/Madrid", airportCode: "PMI" },
  { id: "city-krakow", kind: "city", ru: "Краков", en: "Krakow", countryCode: "PL", timeZone: "Europe/Warsaw", airportCode: "KRK" },
  { id: "city-bucharest", kind: "city", ru: "Бухарест", en: "Bucharest", countryCode: "RO", timeZone: "Europe/Bucharest", airportCode: "OTP" },
  { id: "city-kyiv", kind: "city", ru: "Киев", en: "Kyiv", countryCode: "UA", timeZone: "Europe/Kyiv", airportCode: "KBP" },
  { id: "city-riga", kind: "city", ru: "Рига", en: "Riga", countryCode: "LV", timeZone: "Europe/Riga", airportCode: "RIX" },
  { id: "city-vilnius", kind: "city", ru: "Вильнюс", en: "Vilnius", countryCode: "LT", timeZone: "Europe/Vilnius", airportCode: "VNO" },
  { id: "city-tallinn", kind: "city", ru: "Таллин", en: "Tallinn", countryCode: "EE", timeZone: "Europe/Tallinn", airportCode: "TLL" },
  { id: "city-casablanca", kind: "city", ru: "Касабланка", en: "Casablanca", countryCode: "MA", timeZone: "Africa/Casablanca", airportCode: "CMN" },
  { id: "city-manila", kind: "city", ru: "Манила", en: "Manila", countryCode: "PH", timeZone: "Asia/Manila", airportCode: "MNL" },
  { id: "city-jakarta", kind: "city", ru: "Джакарта", en: "Jakarta", countryCode: "ID", timeZone: "Asia/Jakarta", airportCode: "CGK" },
  { id: "city-osaka", kind: "city", ru: "Осака", en: "Osaka", countryCode: "JP", timeZone: "Asia/Tokyo", airportCode: "KIX" },
  { id: "city-melbourne", kind: "city", ru: "Мельбурн", en: "Melbourne", countryCode: "AU", timeZone: "Australia/Melbourne", airportCode: "MEL" },
  { id: "city-johannesburg", kind: "city", ru: "Йоханнесбург", en: "Johannesburg", countryCode: "ZA", timeZone: "Africa/Johannesburg", airportCode: "JNB" },
  { id: "city-montreal", kind: "city", ru: "Монреаль", en: "Montreal", countryCode: "CA", timeZone: "America/Toronto", airportCode: "YUL" },
  { id: "city-denver", kind: "city", ru: "Денвер", en: "Denver", countryCode: "US", timeZone: "America/Denver", airportCode: "DEN" },
  { id: "city-dallas", kind: "city", ru: "Даллас", en: "Dallas", countryCode: "US", timeZone: "America/Chicago", airportCode: "DFW" },
  { id: "city-houston", kind: "city", ru: "Хьюстон", en: "Houston", countryCode: "US", timeZone: "America/Chicago", airportCode: "IAH" },
  { id: "city-atlanta", kind: "city", ru: "Атланта", en: "Atlanta", countryCode: "US", timeZone: "America/New_York", airportCode: "ATL" },
  { id: "city-washington-dc", kind: "city", ru: "Вашингтон", en: "Washington DC", countryCode: "US", timeZone: "America/New_York", airportCode: "IAD" },
  { id: "city-amman", kind: "city", ru: "Амман", en: "Amman", countryCode: "JO", timeZone: "Asia/Amman", airportCode: "AMM" },

  // --- Cities: "fake geography" airport traps (AC-15a) — own city, NOT merged into the metro whose
  // name the airport is marketed under; searching their own name must surface them on their own.
  { id: "city-girona", kind: "city", ru: "Жирона", en: "Girona", countryCode: "ES", timeZone: "Europe/Madrid", airportCode: "GRO" },
  { id: "city-hahn", kind: "city", ru: "Хан", en: "Hahn", countryCode: "DE", timeZone: "Europe/Berlin", airportCode: "HHN" },
  { id: "city-beauvais", kind: "city", ru: "Бове", en: "Beauvais", countryCode: "FR", timeZone: "Europe/Paris", airportCode: "BVA" },
  { id: "city-bergamo", kind: "city", ru: "Бергамо", en: "Bergamo", countryCode: "IT", timeZone: "Europe/Rome", airportCode: "BGY" },
  { id: "city-sandefjord", kind: "city", ru: "Сандефьорд", en: "Sandefjord", countryCode: "NO", timeZone: "Europe/Oslo", airportCode: "TRF" },
] as const satisfies readonly PlaceRecord[];
