import type { CurrencyCode } from "./currencies";

/** Currency NAMES are data (like place names), searched by prefix in both languages. */
export const CURRENCY_NAMES: Record<CurrencyCode, { ru: string; en: string }> = {
  EUR: { ru: "Евро", en: "Euro" },
  USD: { ru: "Доллар США", en: "US dollar" },
  GBP: { ru: "Британский фунт", en: "British pound" },
  PLN: { ru: "Польский злотый", en: "Polish zloty" },
  UAH: { ru: "Украинская гривна", en: "Ukrainian hryvnia" },
  CZK: { ru: "Чешская крона", en: "Czech koruna" },
  CHF: { ru: "Швейцарский франк", en: "Swiss franc" },
  SEK: { ru: "Шведская крона", en: "Swedish krona" },
  NOK: { ru: "Норвежская крона", en: "Norwegian krone" },
  DKK: { ru: "Датская крона", en: "Danish krone" },
  HUF: { ru: "Венгерский форинт", en: "Hungarian forint" },
  RON: { ru: "Румынский лей", en: "Romanian leu" },
  BGN: { ru: "Болгарский лев", en: "Bulgarian lev" },
  RSD: { ru: "Сербский динар", en: "Serbian dinar" },
  ISK: { ru: "Исландская крона", en: "Icelandic krona" },
  TRY: { ru: "Турецкая лира", en: "Turkish lira" },
  GEL: { ru: "Грузинский лари", en: "Georgian lari" },
  AMD: { ru: "Армянский драм", en: "Armenian dram" },
  AZN: { ru: "Азербайджанский манат", en: "Azerbaijani manat" },
  KZT: { ru: "Казахстанский тенге", en: "Kazakhstani tenge" },
  ILS: { ru: "Израильский шекель", en: "Israeli shekel" },
  AED: { ru: "Дирхам ОАЭ", en: "UAE dirham" },
  EGP: { ru: "Египетский фунт", en: "Egyptian pound" },
  MAD: { ru: "Марокканский дирхам", en: "Moroccan dirham" },
  ZAR: { ru: "Южноафриканский рэнд", en: "South African rand" },
  JPY: { ru: "Японская иена", en: "Japanese yen" },
  CNY: { ru: "Китайский юань", en: "Chinese yuan" },
  KRW: { ru: "Южнокорейская вона", en: "South Korean won" },
  HKD: { ru: "Гонконгский доллар", en: "Hong Kong dollar" },
  SGD: { ru: "Сингапурский доллар", en: "Singapore dollar" },
  THB: { ru: "Тайский бат", en: "Thai baht" },
  VND: { ru: "Вьетнамский донг", en: "Vietnamese dong" },
  IDR: { ru: "Индонезийская рупия", en: "Indonesian rupiah" },
  INR: { ru: "Индийская рупия", en: "Indian rupee" },
  CAD: { ru: "Канадский доллар", en: "Canadian dollar" },
  AUD: { ru: "Австралийский доллар", en: "Australian dollar" },
  NZD: { ru: "Новозеландский доллар", en: "New Zealand dollar" },
  MXN: { ru: "Мексиканский песо", en: "Mexican peso" },
  BRL: { ru: "Бразильский реал", en: "Brazilian real" },
  ARS: { ru: "Аргентинский песо", en: "Argentine peso" },
};
